import type { GuidancePage } from "@/types";

export const GUIDANCE_PAGES: GuidancePage[] = [
  {
    slug: "before-you-arrive",
    title: "Before You Arrive in the UK",
    category: "Documents",
    description: "Everything you need to prepare before you leave for the UK.",
    whatThisIs:
      "A checklist of tasks to complete before you travel to the UK, covering documents, money, accommodation, and your university.",
    whyItMatters:
      "The more you prepare before you leave, the less stressful your arrival will be. Arriving in the UK without the right documents or financial plans can lead to serious problems in your first days.",
    whatToPrepare: [
      "Passport valid for your full stay",
      "BRP collection details",
      "CAS statement",
      "University offer letter",
      "Accommodation confirmation",
      "UK sterling cash",
      "International bank card",
    ],
    stepsToTake: [
      "Confirm your university place and download your CAS statement.",
      "Book and confirm your accommodation — keep the confirmation safe.",
      "Check your passport is valid for at least 6 months beyond your planned return.",
      "Sort your money — tell your bank you are travelling, order UK cash, consider a digital bank.",
      "Plan your airport-to-accommodation route.",
      "Notify your university of your arrival plan.",
    ],
    commonMistakes: [
      "Not downloading the CAS before you leave — you will need it quickly after arrival.",
      "Forgetting to tell your home bank you are travelling — your card may be blocked.",
      "Arriving without accommodation confirmed.",
    ],
    safetyWarning: "Do not share your passport, visa, or financial details with anyone before you travel unless you are dealing with official university or government services.",
    sourceSignpost: "GOV.UK · Your university's international student pages",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide immigration, legal, financial, or visa advice. For official guidance on your student visa, visit GOV.UK or consult your university's international office.",
    relatedTaskIds: ["STU_PRE_001", "STU_PRE_002", "STU_PRE_003", "STU_PRE_005", "STU_PRE_006"],
    lastReviewed: "May 2026",
  },
  {
    slug: "first-24-hours",
    title: "Your First 24 Hours in the UK",
    category: "Safety",
    description: "What to do on arrival day to stay safe and start settling.",
    whatThisIs:
      "A practical guide to your first 24 hours in the UK — from landing to getting settled in your accommodation.",
    whyItMatters:
      "Your first 24 hours set the tone for your entire experience. Staying calm, staying safe, and confirming the essentials means everything else can follow smoothly.",
    whatToPrepare: [
      "Your accommodation address (printed and saved on phone)",
      "Emergency contact numbers",
      "Enough UK cash for transport and food",
      "Your phone charged and ready",
    ],
    stepsToTake: [
      "Travel to your accommodation calmly.",
      "Contact your landlord or university accommodation office.",
      "Check your room — look for any existing damage.",
      "Text family to confirm you have arrived safely.",
      "Charge your phone and activate your SIM/eSIM.",
      "Take photos of your accommodation condition.",
      "Save emergency contacts: UK 999 (emergency services), university emergency line.",
      "Rest — you will be tired and the checklist can continue tomorrow.",
    ],
    commonMistakes: [
      "Trying to do everything at once — focus on safety and rest first.",
      "Not documenting accommodation damage before unpacking.",
      "Leaving bags unattended at any point.",
      "Following unsolicited offers of help from strangers.",
    ],
    safetyWarning: "Be cautious of anyone at the airport offering unsolicited help, taxi services, or asking you to follow them. Use official signs, licensed taxi ranks, or pre-booked services.",
    sourceSignpost: "Metropolitan Police · Action Fraud",
    disclaimer: "NewStart UK provides general settlement guidance only. In an emergency, always call 999. For non-urgent police matters, call 101.",
    relatedTaskIds: ["STU_D1_001", "STU_D1_002", "STU_D1_003", "STU_D1_004", "STU_D1_005"],
    lastReviewed: "May 2026",
  },
  {
    slug: "uk-accommodation-guide",
    title: "Renting in the UK — A Beginner's Guide",
    category: "Accommodation",
    description: "Understanding UK private rental — contracts, deposits, rights, and responsibilities.",
    whatThisIs:
      "A plain-English guide to renting in the UK for the first time. Covers your tenancy agreement, what you are agreeing to, and what your landlord must do.",
    whyItMatters:
      "A tenancy agreement is a legal contract. Many students sign it without reading it carefully. Understanding what you are agreeing to protects you from unexpected costs and unfair treatment.",
    whatToPrepare: [
      "Time to read the full tenancy agreement before signing",
      "Questions about terms you do not understand",
      "A pen or device to take photos of the document",
    ],
    stepsToTake: [
      "Read every page of the tenancy agreement — do not be rushed.",
      "Check: rent amount, deposit amount (maximum 5 weeks' rent), notice period, included bills, repair responsibilities.",
      "Confirm the deposit protection scheme — your landlord must use one by law.",
      "Get the landlord's contact details and save them.",
      "Check the inventory — document the condition of everything before signing.",
      "Ask for a copy of everything you sign.",
      "If anything is unclear — contact Shelter, your university's housing advice service, or Citizens Advice before signing.",
    ],
    commonMistakes: [
      "Signing a contract without reading it fully — verbal promises are not binding.",
      "Not checking the deposit protection scheme — if your landlord has not protected it, they can be fined up to 3x the deposit amount.",
      "Paying a holding deposit before seeing a written agreement.",
      "Assuming the landlord will fix everything — report repairs in writing.",
    ],
    safetyWarning: "Never pay a deposit or holding fee in cash or to an unverified account. Always get a written receipt for any payment. If a deal looks too good to be true, it probably is.",
    sourceSignpost: "Shelter England · Citizens Advice · GOV.UK",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide housing or legal advice. For legal advice on your tenancy, contact Shelter, Citizens Advice, or a qualified housing solicitor.",
    relatedTaskIds: ["STU_PRE_002", "STU_D1_003", "STU_D7_009", "STU_D7_010", "STU_D30_007"],
    lastReviewed: "May 2026",
  },
  {
    slug: "housing-scam-warning",
    title: "How to Spot and Avoid Housing Scams",
    category: "Safety",
    description: "Common housing scams targeting international students — and how to protect yourself.",
    whatThisIs:
      "An alert guide to the most common housing scams targeting international students in the UK, with practical steps to verify properties and landlords.",
    whyItMatters:
      "International students are disproportionately targeted by housing scams. Scammers know that students may not know UK systems and may be under time pressure to find accommodation.",
    whatToPrepare: [
      "A critical eye for deals that seem too good",
      "Time to verify before paying anything",
    ],
    stepsToTake: [
      "Always view a property in person before paying anything.",
      "If you cannot view in person, ask a trusted friend or the university accommodation service to view for you.",
      "Never pay a deposit or holding fee to an overseas account.",
      "Verify the landlord's identity — ask for ID and cross-reference with the property address.",
      "Check the property is listed on a legitimate letting agent's website.",
      "Search the address on Google — see if it appears in multiple listings (a sign of a scam).",
      "Use your university accommodation service — they verify landlords.",
    ],
    commonMistakes: [
      "Paying a deposit before viewing the property.",
      "Transferring money to an overseas bank account — legitimate landlords do not ask for this.",
      "Acting under time pressure — scammers create fake urgency.",
      "Not verifying the landlord's identity.",
    ],
    safetyWarning: "If you have been scammed, report it to Action Fraud at actionfraud.police.uk or call 0300 123 2040. Also tell your university and bank immediately. Do not be embarrassed — it happens to many people.",
    sourceSignpost: "Action Fraud · Shelter England · Your university accommodation service",
    disclaimer: "NewStart UK provides general settlement guidance and scam awareness information only. We do not provide housing or legal advice. Always verify property and landlord credentials independently before making any payment.",
    relatedTaskIds: ["STU_PRE_002", "STU_D1_003", "STU_D30_007"],
    lastReviewed: "May 2026",
  },
  {
    slug: "student-bank-account-prep",
    title: "Opening a UK Student Bank Account — Document Preparation",
    category: "Money",
    description: "What documents you need to open a UK bank account and how to compare your options.",
    whatThisIs:
      "A guide to preparing the documents you need for a UK bank account, plus a comparison of the main student account options.",
    whyItMatters:
      "Opening a UK bank account can take 5–10 days. Starting the process in your first week means you will have access to your funds sooner. Being prepared with the right documents speeds up the process significantly.",
    whatToPrepare: [
      "Passport (valid)",
      "BRP (Biometric Residence Permit) — if you have one",
      "University offer letter or CAS statement",
      "Proof of UK address (university accommodation letter, tenancy agreement, or recent utility bill)",
      "Student ID card",
      "National Insurance number (required by some banks — not all)",
    ],
    stepsToTake: [
      "Compare student bank accounts — look at fees, overdraft limits, perks (e.g. Railcard), and eligibility.",
      "Gather your documents before applying.",
      "Digital banks (Monzo, Starling) are often fastest — you can sometimes start the process before you arrive in the UK.",
      "Book a branch appointment if applying with a traditional bank (Barclays, NatWest, HSBC).",
      "Submit your application and wait for identity and address checks (1–5 working days).",
      "Your PIN will arrive separately by post.",
      "Activate your card and set up mobile banking.",
      "Add your account details to your student loan or scholarship provider.",
    ],
    commonMistakes: [
      "Going to a bank without the correct documents — check requirements before you go.",
      "Assuming your home country bank card will work well for everything — it will not.",
      "Sharing your PIN or online banking details with anyone.",
      "Opening multiple bank accounts — this can affect your credit score.",
    ],
    safetyWarning: "Your bank will never ask you for your PIN, password, or full account details by email or phone. If someone contacts you claiming to be from your bank and asks for this information, hang up and call your bank using the number on your card.",
    sourceSignpost: "UK Finance · FCA · Money Helper",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide financial advice. For guidance on bank accounts and financial products, visit Money Helper (moneyhelper.org.uk) or speak to your bank's student advisor.",
    relatedTaskIds: ["STU_D7_002", "STU_D30_001"],
    lastReviewed: "May 2026",
  },
  {
    slug: "how-to-register-with-a-gp",
    title: "How to Register with a UK GP",
    category: "Health",
    description: "Step-by-step guide to finding and registering with a local doctor (GP) near your university.",
    whatThisIs:
      "A practical guide to finding a GP near your university or term-time address, and completing the registration process.",
    whyItMatters:
      "GP registration is free and gives you access to the NHS — including prescriptions, referrals, and specialist care. Without registering, you will pay for appointments and may not receive the care you need.",
    whatToPrepare: [
      "Your UK address (term-time address)",
      "Details of any ongoing medical conditions or medications",
      "Your previous GP's contact details (for medical records)",
    ],
    stepsToTake: [
      "Use the NHS 'Find a GP' service at nhs.uk/service-search/find-a-gp.",
      "Enter your postcode and see a list of nearby GP surgeries.",
      "Check each surgery's website to confirm they are accepting new patients.",
      "Fill in a GMS1 registration form — available from the surgery website or in person.",
      "Submit the form in person or online.",
      "You do not need to pay anything. You do not need your visa or BRP — GP registration is free for everyone in the UK.",
      "Wait for a confirmation text or letter with your NHS number.",
      "Book a new patient health check once registered.",
    ],
    commonMistakes: [
      "Thinking GP services are not free — they are, for everyone.",
      "Registering with a GP far from where you live — in an emergency, you need to be able to get there.",
      "Not telling your GP about ongoing conditions or medications.",
      "Registering with a private GP instead of an NHS GP — NHS care is free; private care has significant costs.",
    ],
    safetyWarning: "If you are seriously ill or injured and it is not a life-threatening emergency, call NHS 111 or visit nhs.uk. Only call 999 or go to A&E for genuine emergencies.",
    sourceSignpost: "NHS England · UKCISA",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide medical advice. NHS services are free at the point of use. For health advice, contact NHS 111 or your GP.",
    relatedTaskIds: ["STU_D7_003", "STU_D30_002", "STU_D30_010"],
    lastReviewed: "May 2026",
  },
  {
    slug: "nhs-basics",
    title: "NHS Basics — Understanding the UK's Health System",
    category: "Health",
    description: "A plain-English guide to NHS services, how to access them, and what is free.",
    whatThisIs:
      "An overview of how the NHS works — what services are available, how to access them, and what is free versus what has costs.",
    whyItMatters:
      "Many international students come from countries with different health systems. Understanding the NHS means you get the right care at the right time and avoid paying for things that are free.",
    whatToPrepare: [
      "Your NHS number (after GP registration)",
      "The NHS App (download from your app store)",
    ],
    stepsToTake: [
      "Register with a GP as soon as possible after arrival.",
      "Download the NHS App — it lets you book appointments, order prescriptions, and view your health records.",
      "Learn the four main routes to NHS care: NHS 111 (non-emergency, 24/7), your GP (day-to-day), A&E (emergencies only), and pharmacies (minor ailments, no appointment needed).",
      "NHS GP services and NHS 111 are always free.",
      "NHS prescriptions have a fixed cost (£9.90 per item as of April 2024 — free if you are under 19 in full-time education).",
      "A&E is free for everyone. You will not be charged for emergency NHS care regardless of your nationality.",
      "Dental and optician services have costs — register early as NHS places fill up.",
    ],
    commonMistakes: [
      "Going to A&E for non-emergencies — this delays care for people who really need it and may result in charges.",
      "Not registering with a dentist early — NHS dental places are limited.",
      "Assuming you have to pay for all NHS care — most GP and emergency services are free.",
    ],
    safetyWarning: "If you are pregnant, experiencing a mental health crisis, or have a serious ongoing condition, seek NHS help immediately. These services are free and confidential.",
    sourceSignpost: "NHS England · UKCISA",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide medical advice. For health guidance, contact NHS 111 or your GP.",
    relatedTaskIds: ["STU_D7_003", "STU_D7_004", "STU_D30_002", "STU_D30_010", "STU_D90_007"],
    lastReviewed: "May 2026",
  },
  {
    slug: "council-tax-student-exemption",
    title: "Council Tax and the Student Exemption",
    category: "Local Admin",
    description: "What council tax is, why students are exempt, and how to claim it.",
    whatThisIs:
      "A plain-English guide to council tax — what it is, why full-time students do not have to pay it, and the steps to claim your exemption.",
    whyItMatters:
      "Council tax bills can be over £100 per month. Students are exempt — but you must tell the council and prove you are a student. Ignoring council tax letters, even if you are exempt, leads to fines and legal action.",
    whatToPrepare: [
      "Your tenancy agreement",
      "Your student status letter from your university",
      "Your UK address and council tax account reference (if you already have one)",
    ],
    stepsToTake: [
      "Find your local council at gov.uk/find-your-local-council.",
      "Contact the council's council tax department and tell them you are a new full-time student.",
      "Submit your student status letter as proof of your student status.",
      "Ask for written confirmation that your exemption has been applied.",
      "If you receive a bill in your name — do not ignore it. Call the council immediately.",
      "Keep records of all correspondence.",
      "If you live in university halls — the university usually handles this automatically, but check.",
    ],
    commonMistakes: [
      "Ignoring council tax letters because you think you are exempt — always respond.",
      "Assuming your university has told the council — verify it yourself.",
      "If you share with non-students — council tax rules change, seek advice.",
      "Not getting written confirmation — verbal assurances are not enough.",
    ],
    safetyWarning: "Council tax debt can lead to court action, bailiffs, and additional costs. If you receive any council tax letters, respond promptly even if you believe you are exempt.",
    sourceSignpost: "GOV.UK · UKCISA · Your local council",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide legal or financial advice on council tax. For advice, contact Citizens Advice or your local council's student advice service.",
    relatedTaskIds: ["STU_D7_006", "STU_D30_005", "STU_D30_008"],
    lastReviewed: "May 2026",
  },
  {
    slug: "student-status-letter",
    title: "How to Get Your Student Status Letter",
    category: "University",
    description: "What a student status letter is, why you need it, and how to request one from your university.",
    whatThisIs:
      "A guide to the student status letter (sometimes called an enrollment letter or student certificate) — what it is, why banks and councils need it, and how to get one.",
    whyItMatters:
      "You need a student status letter for council tax exemption, opening a bank account, applying for a National Insurance number, and proving your student status to landlords and employers.",
    whatToPrepare: [
      "Your student ID number",
      "The reason you need the letter (specific uses may need specific wording)",
    ],
    stepsToTake: [
      "Check your university website for the student status letter request form.",
      "Some universities process requests through the student portal or international office.",
      "Specify the reason you need the letter — banks and councils sometimes require specific wording.",
      "Allow 3–5 working days for processing.",
      "Collect the letter and check: your name, course, start and end dates, and university contact details are correct.",
      "If the letter is for a council tax exemption, check the council's website for any specific wording requirements.",
    ],
    commonMistakes: [
      "Requesting the letter without specifying why you need it — tailor it to your purpose.",
      "Waiting until you need it urgently — processing takes time.",
      "Not checking the details on the letter before using it.",
    ],
    sourceSignpost: "Your university website and international student office",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide legal or academic advice. Contact your university's international student office for questions about your student status.",
    relatedTaskIds: ["STU_PRE_001", "STU_D7_001", "STU_D30_005", "STU_D30_008"],
    lastReviewed: "May 2026",
  },
  {
    slug: "sim-esim-guide",
    title: "UK Phone Options for Students — SIM and eSIM",
    category: "Local Life",
    description: "Comparing SIM cards and eSIMs for international students, with popular UK providers.",
    whatThisIs:
      "A comparison of SIM cards and eSIMs available in the UK — including popular providers, costs, and what to consider when choosing a plan.",
    whyItMatters:
      "Having a UK phone number quickly after arrival is important for university registration, bank accounts, and landlords. Understanding your options before you buy prevents overpaying.",
    whatToPrepare: [
      "An unlocked phone (check with your current provider)",
      "An idea of your data and call needs",
    ],
    stepsToTake: [
      "Check if your current phone is unlocked — you can usually check with your provider or by trying a different SIM.",
      "Check if your phone supports eSIM (iPhone XS+ and Samsung S20+ generally do).",
      "Compare providers: giffgaff, Smarty, iD Mobile, Lebara, and Lycamobile are popular with students.",
      "Look for SIM-only plans — no contract or 12-month options.",
      "Check data limits, UK call rates, and international call options (if you will call home often).",
      "If arriving before your university SIM card arrives, a prepaid SIM from a convenience shop is a short-term option.",
    ],
    commonMistakes: [
      "Signing a 12-month contract before knowing your data needs.",
      "Using your home SIM abroad — roaming charges can be extremely expensive.",
      "Buying from unofficial sellers — only use registered providers.",
      "Not checking coverage in your area — check provider coverage maps.",
    ],
    sourceSignpost: "Ofcom · Provider websites (giffgaff, Smarty, iD Mobile)",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide financial or telecommunications advice. Compare deals independently before choosing a provider.",
    relatedTaskIds: ["STU_PRE_007", "STU_D1_005"],
    lastReviewed: "May 2026",
  },
  {
    slug: "uk-transport-guide",
    title: "UK Transport — Options and Student Discounts",
    category: "Transport",
    description: "Getting around the UK as a student — trains, buses, London transport, and discount cards.",
    whatThisIs:
      "A practical guide to UK transport options — trains, buses, and London transport — with information on student discounts that can save you hundreds of pounds.",
    whyItMatters:
      "Transport is one of the biggest regular costs for students. Knowing about student discounts before you travel means you start saving from day one.",
    whatToPrepare: [
      "A passport-style photo (for Railcard and Oyster photocard)",
      "Your student ID card",
    ],
    stepsToTake: [
      "Apply for a 16–25 Railcard at railcard.co.uk (£30 per year, 1/3 off most train fares).",
      "If you are in London, apply for a Student Oyster photocard at tfl.gov.uk — this gives 30% off travel.",
      "Download the Trainline and National Rail apps to plan and book journeys.",
      "In cities outside London, local bus services are usually the cheapest option.",
      "If you cycle, check if your university offers bike hire or storage.",
      "Consider a bike if you live close to campus — many UK cities are very cycle-friendly.",
    ],
    commonMistakes: [
      "Not carrying your Railcard on trains — conductors can charge a £10 fine on top of the full fare.",
      "Buying a monthly travel card before checking student discounts.",
      "Not checking if your university runs free campus shuttles.",
    ],
    sourceSignpost: "National Rail · Transport for London · Railcard",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide financial or transport advice. Check current prices and discounts directly with providers as these change regularly.",
    relatedTaskIds: ["STU_PRE_004", "STU_D7_005"],
    lastReviewed: "May 2026",
  },
  {
    slug: "first-month-budget",
    title: "Your First Month Budget — A Guide for International Students",
    category: "Money",
    description: "How to plan and track your spending in your first month in the UK.",
    whatThisIs:
      "A practical budgeting guide for international students in the UK — covering typical costs, how to track spending, and how to build a sustainable budget.",
    whyItMatters:
      "International students often underestimate costs before they arrive. A realistic first-month budget prevents money stress and helps you build sustainable financial habits.",
    whatToPrepare: [
      "Your expected income (loan, scholarship, family support)",
      "Your bank account statements (after a few weeks of spending)",
    ],
    stepsToTake: [
      "List all expected income for the month.",
      "List essential costs: rent, food, transport, phone, internet, course materials.",
      "Set a weekly spending allowance for non-essentials.",
      "Use your bank's app to track spending, or a budgeting app (Emma, Money Dashboard — free).",
      "Review your spending every week — adjust if needed.",
      "Build a small emergency fund — even £10 per week gives you a buffer.",
    ],
    commonMistakes: [
      "Underestimating the cost of food and household items — UK prices are high by international standards.",
      "Not accounting for one-off costs (textbooks, equipment, trips home).",
      "Using credit cards for daily spending — track carefully to avoid debt.",
      "Not reviewing your budget — it changes over time.",
    ],
    safetyWarning: "Avoid high-cost loans, payday loans, or borrowing from informal sources. If you are struggling financially, contact your university's student money advice service — they can help with emergency grants and budgeting advice.",
    sourceSignpost: "Money Helper (MAS) · StepChange Debt Charity · Your university student advice service",
    disclaimer: "NewStart UK provides general settlement guidance and budgeting awareness only. We do not provide financial advice. For free financial guidance, contact Money Helper (moneyhelper.org.uk) or StepChange.",
    relatedTaskIds: ["STU_PRE_005", "STU_D30_004", "STU_D90_001", "STU_D90_008"],
    lastReviewed: "May 2026",
  },
  {
    slug: "tenancy-documents",
    title: "Understanding Your Tenancy Agreement",
    category: "Accommodation",
    description: "What to look for in a UK tenancy agreement before you sign.",
    whatThisIs:
      "A plain-English guide to reading and understanding a UK tenancy agreement — what each section means and what to look out for.",
    whyItMatters:
      "Your tenancy agreement is a legally binding contract. Signing one without understanding it can lead to unexpected costs, unfair terms, and difficulty getting your deposit back.",
    whatToPrepare: [
      "Time to read the full document before signing",
      "Questions to ask — write them down before you read",
    ],
    stepsToTake: [
      "Read every clause — do not sign until you have read the whole thing.",
      "Check: the rent amount and due date, the deposit amount and protection scheme, the notice period, the start and end date, what is included in rent, what repairs are your responsibility vs the landlord's.",
      "Note any clauses about: guests, pets, smoking, quiet hours, changing locks.",
      "Ask the landlord or letting agent to explain anything you do not understand.",
      "If anything is unclear — seek advice from Shelter, your university's housing advice service, or Citizens Advice before signing.",
      "Keep a copy of everything you sign.",
    ],
    commonMistakes: [
      "Being rushed to sign — a legitimate landlord will give you time to read.",
      "Relying on verbal explanations that are not in the contract.",
      "Not knowing the notice period — if you want to leave early, you need to know your obligations.",
      "Signing a contract with unfair terms because you did not read it.",
    ],
    safetyWarning: "If you are pressured to sign quickly or told 'everyone signs this anyway' — this is a warning sign. Take your time. Get advice if needed.",
    sourceSignpost: "Shelter England · Citizens Advice · GOV.UK",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide legal or housing advice. For legal advice on your tenancy, contact Shelter, Citizens Advice, or a qualified housing solicitor.",
    relatedTaskIds: ["STU_D7_009", "STU_D30_007", "STU_D90_003"],
    lastReviewed: "May 2026",
  },
  {
    slug: "deposit-protection",
    title: "Tenant Deposit Protection — What You Need to Know",
    category: "Accommodation",
    description: "How the UK's tenant deposit protection schemes work and how to get your deposit back.",
    whatThisIs:
      "A guide to the UK tenant deposit protection scheme — your rights, how deposits are protected, and how to dispute deductions at the end of your tenancy.",
    whyItMatters:
      "Your deposit is often £500–£2,000. By law, your landlord must protect it in a government-approved scheme. If they do not, you can take legal action and claim compensation — up to 3x the deposit amount.",
    whatToPrepare: [
      "Your tenancy agreement",
      "Your deposit payment receipt",
      "Photos of your accommodation condition at check-in",
    ],
    stepsToTake: [
      "Ask your landlord which deposit protection scheme they have used — they must tell you within 30 days.",
      "Check the scheme directly: MyDeposits, DPS (Deposit Protection Service), or TDS (Tenancy Deposit Scheme).",
      "You should receive a 'certificate of protection' — keep this safe.",
      "At check-out, the landlord must provide a breakdown of any deductions within 10 days.",
      "If you disagree with deductions — use the scheme's free dispute resolution service.",
      "Keep your check-in photos as evidence.",
    ],
    commonMistakes: [
      "Not knowing which scheme holds your deposit.",
      "Accepting deductions without challenging them — use the dispute service if you disagree.",
      "Not reading the inventory report at check-in — this is your evidence.",
      "Leaving without doing a check-out inspection — insist on one.",
    ],
    safetyWarning: "If your landlord has not protected your deposit within 30 days, you can take them to court and receive compensation of between 1x and 3x the deposit amount. Contact Shelter or a housing solicitor.",
    sourceSignpost: "GOV.UK · MyDeposits · DPS · TDS · Shelter England",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide legal or housing advice. For advice on deposit disputes, contact Shelter, Citizens Advice, or a housing solicitor.",
    relatedTaskIds: ["STU_D7_010", "STU_D1_004", "STU_D30_007", "STU_D90_003"],
    lastReviewed: "May 2026",
  },
  {
    slug: "part-time-work-awareness",
    title: "Part-Time Work While Studying in the UK",
    category: "Work",
    description: "Your rights, conditions, and practical steps for working part-time as an international student.",
    whatThisIs:
      "A guide to working part-time in the UK as an international student — including work hour limits, National Insurance, your rights as a worker, and job scam warnings.",
    whyItMatters:
      "Many international students want to work part-time. Knowing the rules protects your visa, your studies, and your rights as a worker in the UK.",
    whatToPrepare: [
      "Your visa conditions (check your passport or BRP)",
      "Your NI number (once you have one)",
      "An updated CV",
    ],
    stepsToTake: [
      "Confirm your work rights — Student Route visa holders can work up to 20 hours per week during term time.",
      "Apply for your NI number if you do not have one yet.",
      "Use your university careers service for vetted part-time job listings.",
      "Check your contract carefully before accepting — know your hourly rate and hours.",
      "Keep payslips for your tax records.",
      "Speak to your university if work is affecting your studies.",
    ],
    commonMistakes: [
      "Working more than 20 hours during term time — this can affect your visa status.",
      "Accepting cash-in-hand work — this is illegal, you have no employment rights, and you may owe unpaid tax.",
      "Not knowing your rights as a worker — you are entitled to the National Minimum Wage, rest breaks, and a safe working environment.",
    ],
    safetyWarning: "If you are not paid the National Minimum Wage, are asked to work off the books, or experience any form of exploitation in the workplace, contact your university's student advice service or the Acas helpline (0300 123 1100).",
    sourceSignpost: "UKCISA · GOV.UK · Acas",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide legal, immigration, or employment advice. For advice on your employment rights, contact Acas or a qualified employment solicitor.",
    relatedTaskIds: ["STU_D30_003", "STU_D30_006", "STU_D30_009", "STU_D90_005"],
    lastReviewed: "May 2026",
  },
  {
    slug: "ni-number-basics",
    title: "National Insurance Number — Explained",
    category: "Work",
    description: "What an NI number is, why you need it, and how to apply for one.",
    whatThisIs:
      "A plain-English guide to the UK National Insurance number — what it is, why you need it, and how to get one.",
    whyItMatters:
      "You need an NI number to work legally in the UK and to access certain state benefits. If you plan to work, you need this number.",
    whatToPrepare: [
      "Your passport or BRP",
      "Your UK address",
    ],
    stepsToTake: [
      "You may be assigned an NI number automatically when you start work — your employer will contact you.",
      "If you have not received one by the time you start work, apply at gov.uk/apply-national-insurance-number.",
      "Keep your NI number safe — do not share it publicly or with anyone other than your employer and HMRC.",
      "You can also call HMRC to check: 0300 200 3310.",
    ],
    commonMistakes: [
      "Working without an NI number for a long period — your employer may be fined.",
      "Sharing your NI number publicly or on social media — treat it like a password.",
      "Losing your NI number — you can find it on previous payslips or by calling HMRC.",
    ],
    sourceSignpost: "GOV.UK (HMRC)",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide financial or tax advice. For NI and tax queries, contact HMRC directly at gov.uk/contact-hmrc.",
    relatedTaskIds: ["STU_D30_003", "STU_D30_006"],
    lastReviewed: "May 2026",
  },
  {
    slug: "right-to-work-share-code",
    title: "Your Right to Work in the UK",
    category: "Work",
    description: "Understanding your right to work as an international student and how to use the share code system.",
    whatThisIs:
      "A guide to right-to-work checks and the share code system — what your rights are and how employers verify your status.",
    whyItMatters:
      "Your right to work in the UK depends on your visa type. Employers are legally required to check this. Understanding your status protects you from exploitation and ensures you do not accidentally break the law.",
    whatToPrepare: [
      "Your passport or BRP",
      "Your CAS number",
    ],
    stepsToTake: [
      "Confirm your work rights based on your visa — Student Route visa holders can work up to 20 hours per week during term time.",
      "Your employer will ask to see your passport or BRP and may check your status online using a share code.",
      "You can generate a share code at gov.uk/prove-right-to-work — this lets employers check your status securely.",
      "You do not need to share your visa details with your employer — only the share code check.",
    ],
    commonMistakes: [
      "Working more hours than your visa allows — this can lead to visa cancellation.",
      "Not knowing your exact work conditions — check your visa carefully.",
      "Assuming all jobs are fine — some roles have additional restrictions for international students.",
    ],
    safetyWarning: "If an employer asks you to work more hours than your visa allows, refuses to give you payslips, or makes other demands that feel wrong, contact your university careers service or the Acas helpline.",
    sourceSignpost: "GOV.UK · UKCISA",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide immigration or legal advice. For official guidance on your visa conditions, visit GOV.UK or consult your university's international office.",
    relatedTaskIds: ["STU_D30_003", "STU_D30_006", "STU_D30_009", "STU_D90_005"],
    lastReviewed: "May 2026",
  },
  {
    slug: "job-scam-warning",
    title: "Job and Employment Scams — How to Spot Them",
    category: "Safety",
    description: "Common job scams targeting international students — and how to protect yourself.",
    whatThisIs:
      "An alert guide to the most common job and employment scams targeting international students in the UK.",
    whyItMatters:
      "Job scams are increasingly sophisticated and common. Scammers specifically target international students who may not know UK employment systems and may need money urgently.",
    whatToPrepare: [
      "An awareness of common scam tactics",
      "A critical eye for offers that seem too good",
    ],
    stepsToTake: [
      "Only use reputable job platforms — your university careers service, Indeed, LinkedIn, and Glassdoor.",
      "Research any company before applying — check their website, reviews, and Companies House registration.",
      "Never pay money to get a job — legitimate employers do not charge recruitment fees.",
      "Be wary of guaranteed job offers — no employer can guarantee employment.",
      "Check the salary — if it is significantly higher than market rates, be suspicious.",
      "Never give your bank details to a potential employer until you have a signed contract.",
      "Trust your instincts — if something feels wrong, walk away.",
    ],
    commonMistakes: [
      "Paying a fee to 'process' your application — this is always a scam.",
      "Giving bank details before a contract is signed.",
      "Acting under pressure — legitimate employers do not create artificial urgency.",
      "Not checking if a company is registered — use Companies House (companieshouse.gov.uk).",
    ],
    safetyWarning: "If you have been targeted by a job scam, report it to Action Fraud at actionfraud.police.uk. If you have given bank details, contact your bank immediately. If you have paid money, your university may be able to help.",
    sourceSignpost: "Action Fraud · GOV.UK · Your university careers service",
    disclaimer: "NewStart UK provides general settlement guidance and scam awareness only. We do not provide employment or legal advice. Always verify job offers independently before proceeding.",
    relatedTaskIds: ["STU_D30_006", "STU_D30_009", "STU_D90_005"],
    lastReviewed: "May 2026",
  },
  {
    slug: "emergency-contacts",
    title: "Emergency Contacts and Where to Get Help",
    category: "Safety",
    description: "The key emergency numbers and support services you need in the UK.",
    whatThisIs:
      "A reference list of emergency numbers, helplines, and support services available to international students in the UK.",
    whyItMatters:
      "In a crisis, you need to know who to call quickly. Having this list means you can get help without wasting time searching.",
    whatToPrepare: [
      "Save these numbers in your phone",
      "Save the numbers for your university's support services",
    ],
    stepsToTake: [
      "Save 999 in your phone — for life-threatening emergencies (police, ambulance, fire).",
      "Save 111 in your phone — for non-emergency medical help and advice.",
      "Save 101 in your phone — for non-urgent police matters.",
      "Save your university's emergency and student support numbers.",
      "Save Action Fraud: 0300 123 2040 — for reporting fraud.",
      "Save Samaritans: 116 123 — for emotional support (free, 24/7).",
      "Save your accommodation landlord's emergency contact.",
    ],
    commonMistakes: [
      "Calling 999 for non-emergencies — use 111 or 101 for non-emergencies.",
      "Not saving university support numbers — you need them quickly.",
    ],
    safetyWarning: "In any life-threatening emergency — always call 999 first. If you are not sure whether it is an emergency, call 111 and they will advise you.",
    sourceSignpost: "NHS England · Metropolitan Police · Action Fraud · Samaritans",
    disclaimer: "NewStart UK provides general settlement guidance and emergency contact information. In a genuine emergency, always call 999. For non-emergency support, contact the relevant service directly.",
    relatedTaskIds: ["STU_D1_001", "STU_D1_002", "STU_D90_010"],
    lastReviewed: "May 2026",
  },
  {
    slug: "90-day-review",
    title: "Your 90-Day Settlement Review",
    category: "Growth",
    description: "A structured self-review to complete at the end of your first 90 days in the UK.",
    whatThisIs:
      "A structured self-review guide for international students to complete after 90 days in the UK — checking what is complete, what needs attention, and what is going well.",
    whyItMatters:
      "90 days is the end of your initial settlement window. A structured review helps you see what you have achieved, identify gaps, and plan your next steps — both for yourself and for reporting to sponsors or family.",
    whatToPrepare: [
      "Your NewStart UK checklist progress",
      "Notes on what felt difficult or confusing",
      "Your bank statements for the last month",
    ],
    stepsToTake: [
      "Go through your NewStart UK checklist and mark all completed tasks.",
      "Identify any tasks still incomplete — note why and whether they still matter.",
      "Review your finances — is your budget working? Do you need to adjust?",
      "Check your housing — are there any unresolved issues?",
      "Check your health — GP registered, NHS number received?",
      "Reflect on your emotional wellbeing — are you settling in? Do you need support?",
      "Update your sponsor or family on your progress.",
      "Note what surprised you — this is useful for yourself and for other students who come after you.",
      "Set goals for the next 90 days — academic, financial, social, and practical.",
    ],
    commonMistakes: [
      "Not reviewing — small problems left alone tend to grow.",
      "Being too hard on yourself — the first 90 days are a learning curve.",
      "Not updating sponsors or family until there is a problem.",
    ],
    sourceSignpost: "NewStart UK · Your university student support services",
    disclaimer: "NewStart UK provides general settlement guidance only. We do not provide legal, financial, or immigration advice. For specific concerns, contact the relevant official service or qualified professional.",
    relatedTaskIds: ["STU_D90_001", "STU_D90_002", "STU_D90_003", "STU_D90_004", "STU_D90_005", "STU_D90_006"],
    lastReviewed: "May 2026",
  },
];
