import type { Task } from "@/types";

export const SEED_TASKS: Task[] = [
  // ─── PRE-ARRIVAL (before travel) ───────────────────────────────────────────
  {
    taskId: "STU_PRE_001",
    title: "Confirm your university enrolment instructions",
    summary: "Make sure you know exactly what steps are needed to confirm your place at your university — before you travel.",
    stage: "PRE",
    category: "University",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Your university enrolment confirmation is your proof of student status. Without it, you cannot open a student bank account, get council tax exemption, or access many other UK services. Confirming early means you have time to fix any issues before you arrive.",
    whatToPrepare: [
      "Your offer letter or CAS (Confirmation of Acceptance for Studies) number",
      "Passport and visa details",
      "University portal login details",
    ],
    stepsToTake: [
      "Log into your university applicant or student portal.",
      "Follow any 'Accept Offer' or 'Confirm Enrolment' steps if not already done.",
      "Download or screenshot your enrolment confirmation letter.",
      "Note your student ID number — you will need it for everything.",
      "Check if your university requires an in-person check-in on arrival.",
    ],
    commonMistakes: [
      "Assuming enrolment is automatic — you usually need to actively confirm.",
      "Not downloading the confirmation letter before arriving in the UK.",
      "Missing the deadline to accept your offer — check your offer email carefully.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Check your university offer email for the exact portal URL. Each university uses a different portal (UCAS, UniBuddy, or their own system).",
  },
  {
    taskId: "STU_PRE_002",
    title: "Confirm your accommodation and first-night plan",
    summary: "Have a confirmed place to stay on your first night before you travel to the UK.",
    stage: "PRE",
    category: "Accommodation",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 45,
    whyItMatters:
      "Arriving in a new city with nowhere confirmed to stay is stressful and expensive. Hotel prices near universities surge in September. Book something confirmed before you travel — even if it is temporary.",
    whatToPrepare: [
      "Accommodation booking confirmation (email or PDF)",
      "Address of the accommodation",
      "Contact number for your landlord or halls warden",
      "Directions from the airport or station",
    ],
    stepsToTake: [
      "Confirm your university accommodation booking is fully accepted.",
      "If renting privately: get written confirmation of your booking and deposit payment.",
      "Save the address, postcode, and contact number in your phone.",
      "Plan your route from the airport or train station to your accommodation.",
      "If arriving late at night, confirm your check-in process (key collection, code entry, etc.).",
    ],
    commonMistakes: [
      "Assuming university halls are ready on the same day your course starts — they are usually ready from a specific date.",
      "Booking accommodation at the last minute in September — prices jump significantly.",
      "Not saving the UK mobile number or WhatsApp of the landlord or warden.",
    ],
    riskWarning:
      "Never transfer money to an unverified landlord before seeing written confirmation and evidence of ownership. See the Housing Scam Warning guide for red flags.",
    sourceSignpost:
      "University halls: contact your university's accommodation office. Private rental: use Rightmove, Zoopla, or a letting agent registered with the TPO (The Property Ombudsman).",
  },
  {
    taskId: "STU_PRE_003",
    title: "Prepare key document copies",
    summary: "Make digital and physical copies of your most important travel and identity documents before leaving.",
    stage: "PRE",
    category: "Documents",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: false,
    estimatedMinutes: 30,
    whyItMatters:
      "UK border control may ask to see your passport, visa, and CAS. You will need copies of these documents to open bank accounts, register with a GP, and prove your right to study. Losing originals abroad without copies is extremely difficult to fix.",
    whatToPrepare: [
      "Passport (valid for at least 6 months beyond your planned stay)",
      "BRP (Biometric Residence Permit) if already issued",
      "CAS letter from your university",
      "Travel insurance certificate",
      "University acceptance letter",
      "Proof of accommodation",
    ],
    stepsToTake: [
      "Photograph or scan every document listed above.",
      "Save digital copies in a secure cloud folder (Google Drive, iCloud, etc.).",
      "Email copies to yourself so you can access them from any device.",
      "Keep physical copies separate from the originals in your hand luggage.",
      "Check your passport expiry date — UKVI recommends it is valid for at least 6 months beyond your arrival date.",
    ],
    commonMistakes: [
      "Storing copies only on one device that could be lost or stolen.",
      "Not checking passport validity — some students arrive to find their passport expires in under 6 months.",
      "Keeping all documents in checked luggage — always keep them in your hand luggage.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "UKVI passport validity guidance: gov.uk/guidance/immigration-rules/immigration-rules-appendix-fm-1-7",
  },
  {
    taskId: "STU_PRE_004",
    title: "Plan your airport-to-accommodation route",
    summary: "Know exactly how you will get from the airport to your accommodation before you travel.",
    stage: "PRE",
    category: "Transport",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Arriving in an unfamiliar city after a long flight is disorienting. Planning your route in advance removes one major source of stress. Pre-booking transport also means you know the exact cost upfront.",
    whatToPrepare: [
      "Postcode of your accommodation (check your confirmation email)",
      "Flight arrival time (including expected delays)",
      "Transport options from your arrival airport",
    ],
    stepsToTake: [
      "Look up the cheapest and fastest transport options from your arrival airport to your city.",
      "Check if your university runs a free or low-cost arrival shuttle — many do in September.",
      "Pre-book a taxi or airport transfer if arriving late or with heavy luggage.",
      "Save the route in Google Maps offline or screenshot the directions.",
      "If using public transport, check if you can load an Oyster card or contactless bank card for London, or the equivalent for your city.",
    ],
    commonMistakes: [
      "Not accounting for arrival delays — always add at least 1–2 hours buffer.",
      "Assuming you can just get a taxi at the airport — these can be expensive and scarce at busy times.",
      "Not checking if your phone works in the UK immediately on arrival.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "National Rail: nationalrail.co.uk | Transport for London: tfl.gov.uk | Megabus: uk.megabus.com | National Express: nationalexpress.com",
  },
  {
    taskId: "STU_PRE_005",
    title: "Sort your money before travel — currency, cards, and emergency cash",
    summary: "Have the right financial setup before you arrive so you are not stranded without access to money.",
    stage: "PRE",
    category: "Money",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "Using a standard UK bank card from home can mean expensive foreign transaction fees. Some UK card machines do not accept foreign cards, especially for small purchases. Arriving with a mix of cash and a UK-ready card means you can buy food, travel, and pay rent without problems.",
    whatToPrepare: [
      "A debit or credit card that works internationally (check with your bank)",
      "Some GBP cash (around £100–200 for your first few days)",
      "Knowledge of your bank's international fee structure",
    ],
    stepsToTake: [
      "Contact your home bank to inform them you are travelling to the UK — this prevents your card being blocked for fraud.",
      "Ask about international withdrawal and transaction fees.",
      "Consider getting a travel money card (e.g. Wise, Revolut) that uses the real exchange rate.",
      "Exchange some GBP before you travel — airports usually have poor rates so try to get a small amount in advance.",
      "Save your bank's emergency contact number in your phone.",
    ],
    commonMistakes: [
      "Not telling your bank you are travelling, resulting in your card being blocked.",
      "Exchanging too much cash at airport bureaux de change — rates are significantly worse than the high street.",
      "Relying entirely on a card that only works at specific ATMs.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "MoneyHelper (part of MoneySavingExpert): moneyhelper.org.uk | Wise: wise.com | Revolut: revolut.com",
  },
  {
    taskId: "STU_PRE_006",
    title: "Check your visa and BRP entry clearance details",
    summary: "Confirm your student visa details are correct before you travel to avoid problems at the UK border.",
    stage: "PRE",
    category: "Documents",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: false,
    estimatedMinutes: 20,
    whyItMatters:
      "Your visa and BRP are your legal proof of right to be in the UK. Border Force officers can ask you to prove the purpose of your visit. Having your documents in order means a smooth arrival — and avoids the stress of being questioned or delayed.",
    whatToPrepare: [
      "Passport with valid student visa vignette or stamp",
      "BRP collection notice letter (if your BRP will be collected from a Post Office)",
      "CAS letter from your university",
      "Proof of funds (bank statements showing maintenance funds)",
    ],
    stepsToTake: [
      "Check that your passport has been stamped with a valid entry clearance vignette.",
      "Read your BRP collection letter carefully — it tells you where and when to collect your BRP (usually within 10 days of arriving).",
      "Note the deadline for BRP collection — missing it can result in fines.",
      "Check that the name, date of birth, and visa details on your passport match your university records.",
    ],
    commonMistakes: [
      "Not collecting the BRP within the stated deadline — this is a legal requirement.",
      "Losing the BRP collection letter — you need it to collect your BRP.",
      "Arriving with the wrong type of entry stamp — confirm you have the correct student entry clearance.",
    ],
    riskWarning:
      "If you have any concerns about your visa status, contact your university's international student support team immediately before travelling.",
    sourceSignpost:
      "UKVI BRP collection: gov.uk/biometric-residence-permit | Student visa guidance: gov.uk/student-visa",
  },
  {
    taskId: "STU_PRE_007",
    title: "Research UK phone options — SIM vs eSIM",
    summary: "Understand how to get a working UK phone number before or shortly after you arrive.",
    stage: "PRE",
    category: "Local Life",
    priority: "Medium",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 15,
    whyItMatters:
      "A UK phone number is essential for opening a bank account, verifying accounts, and contacting landlords and universities. Many services will not accept a foreign phone number for verification codes.",
    whatToPrepare: [
      "Your current phone — check if it is SIM-locked",
      "Research on UK SIM and eSIM providers",
    ],
    stepsToTake: [
      "Check if your current phone is locked to your home network — if so, you may need to unlock it or use a UK SIM.",
      "Consider an eSIM (digital SIM) — you can activate it before arrival so you have UK data immediately.",
      "Compare UK SIM-only plans — giffgaff, Lebara, Voxi, Smarty, and iD Mobile are popular student choices.",
      "If using your home SIM, enable international roaming before you leave.",
    ],
    commonMistakes: [
      "Arriving without any UK data plan and being unable to use maps or check emails.",
      "Signing a long SIM contract before comparing options — SIM-only plans are flexible and usually month-to-month.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "giffgaff: giffgaff.com | Lebara: lebara.com | Voxi: voxi.co.uk | Smarty: smarty.co.uk",
  },
  {
    taskId: "STU_PRE_008",
    title: "Notify your university of your arrival plan",
    summary: "Tell your university when and where you are arriving so they can support you.",
    stage: "PRE",
    category: "University",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 10,
    whyItMatters:
      "Universities use arrival information to coordinate welcome services, airport pickups, and check-in sessions. Notifying them means they know to expect you and can follow up if you do not arrive as planned.",
    whatToPrepare: [
      "Your student ID number",
      "Expected arrival date and time",
      "Accommodation address",
    ],
    stepsToTake: [
      "Check your university portal for an 'Arrival Notification' or 'Welcome Form'.",
      "Fill in your expected arrival date and accommodation details.",
      "Note any airport pick-up services your university offers in September.",
    ],
    commonMistakes: [
      "Assuming you do not need to tell them — most universities actively ask for this information.",
      "Not updating your arrival details if plans change.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Contact your university's international student support team via their official contact details (not through social media).",
  },

  // ─── ARRIVAL DAY ──────────────────────────────────────────────────────────────
  {
    taskId: "STU_D1_001",
    title: "Arrive safely and confirm accommodation access",
    summary: "Get to your accommodation safely and confirm you can access it before doing anything else.",
    stage: "D1",
    category: "Safety",
    priority: "Very High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 60,
    whyItMatters:
      "Your first priority on arrival is personal safety and a secure base. Long-haul travel is exhausting and judgment can be impaired. Get to your accommodation, rest, and deal with admin tasks after you have settled in physically.",
    whatToPrepare: [
      "Confirmed accommodation address (saved in phone and as a printed card)",
      "Airport-to-accommodation transport already pre-booked",
      "Emergency contact number saved in your phone",
    ],
    stepsToTake: [
      "Follow your pre-planned route to your accommodation.",
      "Once inside, check that locks, windows, and basic facilities (heating, hot water) are working.",
      "If there are immediate problems, contact your landlord or university accommodation office immediately.",
      "Text your emergency contact to let them know you have arrived safely.",
      "Rest — do not try to do everything on day one.",
    ],
    commonMistakes: [
      "Trying to do too much on the first day — fatigue increases the chance of making expensive or risky decisions.",
      "Not checking the accommodation condition and missing a problem that becomes harder to resolve later.",
    ],
    riskWarning:
      "If you feel unsafe at any point, leave and go to a public place. Call 999 for emergencies.",
    sourceSignpost: "UK Emergency Services: 999 | Non-emergency police: 101",
  },
  {
    taskId: "STU_D1_002",
    title: "Text family or emergency contact with safe arrival",
    summary: "Let your family or emergency contact know you have arrived safely in the UK.",
    stage: "D1",
    category: "Safety",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 5,
    whyItMatters:
      "Long-haul travel with family worried about you is stressful for everyone. A quick message when you arrive takes seconds and gives everyone peace of mind.",
    whatToPrepare: ["Emergency contact saved in your phone with their UK number or WhatsApp"],
    stepsToTake: [
      "Send a quick message when you land and again when you reach your accommodation.",
      "Share your accommodation address and local contact number once you have one.",
      "Agree on a check-in schedule so they know when to expect to hear from you.",
    ],
    commonMistakes: [
      "Forgetting to text because you are busy — your family may worry and try to contact you urgently.",
    ],
    riskWarning: undefined,
    sourceSignpost: undefined,
  },
  {
    taskId: "STU_D1_003",
    title: "Collect keys and inspect your accommodation",
    summary: "Collect your accommodation keys and do a quick inspection of the property condition.",
    stage: "D1",
    category: "Accommodation",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "The condition of your accommodation at move-in is your baseline. If you do not record it now and something is damaged or not working, you could be wrongly charged when you move out.",
    whatToPrepare: [
      "Key collection process (check-in email should have this)",
      "Your tenancy agreement to reference the move-in condition clause",
      "A phone camera to take photos",
    ],
    stepsToTake: [
      "Collect all sets of keys and any access fobs or cards.",
      "Walk through every room and check: walls, floors, windows, appliances, bathroom, kitchen.",
      "Take timestamped photos of everything — especially any existing damage, stains, or faults.",
      "Report any pre-existing damage to your landlord or university accommodation office in writing (email is fine) on the same day.",
      "Keep copies of all correspondence.",
    ],
    commonMistakes: [
      "Not taking photos — this is the most important thing you can do to protect your deposit.",
      "Assuming the landlord will automatically know about existing damage — you must report it in writing.",
      "Waiting days before reporting a problem — the longer you wait, the harder it is to prove it was pre-existing.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Tenancy deposit protection: gov.uk/tenancy-deposit-protection | If you rent from a letting agent: they must be registered with a government-approved scheme (TDS, DPS, or MyDeposits).",
  },
  {
    taskId: "STU_D1_004",
    title: "Take timestamped photos of accommodation condition",
    summary: "Photograph every room of your accommodation on move-in day as deposit protection.",
    stage: "D1",
    category: "Accommodation",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Your tenancy deposit is typically 5 weeks' rent. Without timestamped photos, you have no proof of pre-existing damage if your landlord tries to charge you at the end of your tenancy.",
    whatToPrepare: ["A smartphone with a camera", "Your tenancy agreement"],
    stepsToTake: [
      "Photograph every room from multiple angles — corners, ceilings, floors, appliances.",
      "Include close-up shots of any existing damage, stains, or wear.",
      "Enable timestamp on your photos (most phone cameras do this automatically).",
      "Save photos to a cloud folder and email a copy to yourself.",
      "Note the date in your photos' description if your camera does not embed it.",
    ],
    commonMistakes: [
      "Only taking wide shots — close-ups of specific damage are more useful.",
      "Not saving photos in multiple places — phones can be lost or reset.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Shelter England: shelterengland.org | Shelter Scotland: shelter.scot | Citizens Advice: citizensadvice.org.uk",
  },
  {
    taskId: "STU_D1_005",
    title: "Charge your UK phone and activate SIM or eSIM",
    summary: "Get your UK phone number working as soon as possible after arrival.",
    stage: "D1",
    category: "Local Life",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Your UK phone number is needed for banking, NHS registration, delivery confirmations, and university verification. Many UK services will only send verification codes to a UK number.",
    whatToPrepare: [
      "Your phone (SIM or eSIM ready)",
      "Your chosen UK SIM or eSIM activation details",
    ],
    stepsToTake: [
      "Insert your UK SIM card or activate your eSIM plan.",
      "Top up with credit or activate your monthly plan.",
      "Test that you can make calls, send texts, and use mobile data.",
      "Save your new UK number in your phone contacts under 'My Number'.",
      "If you have a UK landline number for your accommodation, save that too.",
    ],
    commonMistakes: [
      "Waiting too long to set up a UK SIM — many essential services need a UK number immediately.",
      "Not checking that your phone is unlocked for UK SIM use before travelling.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Ofcom coverage checker: broadbandchecker.ofcom.org.uk | Which? mobile network reviews: which.co.uk",
  },
  {
    taskId: "STU_D1_006",
    title: "Register with your university — confirm enrolment in person",
    summary: "Complete your university registration in person if required, or confirm online registration is complete.",
    stage: "D1",
    category: "University",
    priority: "Very High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 45,
    whyItMatters:
      "Being fully registered with your university is required to access your student loan, get your student ID, use the library, and claim your student status for discounts. Some universities require in-person check-in at specific times — missing this can affect your place.",
    whatToPrepare: [
      "Passport",
      "BRP",
      "CAS letter",
      "Proof of address (your accommodation address)",
    ],
    stepsToTake: [
      "Check your university portal to see if registration is online or in-person.",
      "If in-person: go to the registration desk as early as possible — queues are longest on day one.",
      "If online: confirm each step is complete and download or screenshot your confirmation.",
      "Collect your university ID card — you need it for the library, buildings, and student discounts.",
    ],
    commonMistakes: [
      "Assuming online registration is automatic — check every step.",
      "Not collecting your student ID on the first available day — queues get very long.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Your university's international student support team is your first point of contact for any enrolment issues.",
  },

  // ─── FIRST WEEK ──────────────────────────────────────────────────────────────
  {
    taskId: "STU_D7_001",
    title: "Complete university check-in and collect your student ID",
    summary: "Finish all university registration steps and get your physical student ID card.",
    stage: "D7",
    category: "University",
    priority: "Very High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 60,
    whyItMatters:
      "Your student ID is your proof of student status — you need it for library access, exam entry, building access, and student discounts. Without completing registration, you may not be able to access your student loan or course materials.",
    whatToPrepare: [
      "Passport and BRP",
      "University portal login",
      "Proof of address",
    ],
    stepsToTake: [
      "Log into the student portal and confirm all registration steps are marked complete.",
      "Visit the student ID card desk to collect your card (if not done on arrival day).",
      "Check that your name and photo are correct on the card.",
      "Note your student ID number and save it somewhere accessible.",
      "If there is a formal enrollment or matriculation ceremony, attend it.",
    ],
    commonMistakes: [
      "Assuming that receiving an offer email means you are fully enrolled — universities have a formal registration process.",
      "Not checking your student email inbox — the university will use this for all official communication.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Your student portal is the single source of truth for all university admin. Bookmark it now.",
  },
  {
    taskId: "STU_D7_002",
    title: "Research and compare UK student bank account options",
    summary: "Look at the different student bank accounts available so you can make an informed choice before opening one.",
    stage: "D7",
    category: "Money",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "Student bank accounts in the UK often come with free overdrafts (up to £1,000–£3,000 interest-free) and other perks. Choosing the right one early means you have a proper UK account for rent, part-time work wages, and student discounts.",
    whatToPrepare: [
      "Your passport and BRP",
      "Proof of university enrolment (student ID or letter)",
      "Proof of UK address (tenancy agreement or accommodation letter)",
    ],
    stepsToTake: [
      "Research student bank accounts — major providers include: Santander, HSBC, NatWest, Lloyds, Barclays.",
      "Compare: overdraft limit, monthly fee, interest rate, and any freebies (railcards, Amazon vouchers).",
      "Check eligibility criteria — most require proof of UK address and student status.",
      "Note which banks have branches near your university or accommodation.",
      "Make a shortlist of your top two choices before visiting a branch.",
    ],
    commonMistakes: [
      "Opening an account at the first bank you visit without comparing options — different banks have very different offers.",
      "Not checking whether the overdraft is interest-free while you are a student.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "MSE (MoneySavingExpert) student bank account guide: moneysavingexpert.com | Which? student bank accounts: which.co.uk",
  },
  {
    taskId: "STU_D7_003",
    title: "Find a local GP surgery and register as a patient",
    summary: "Register with a NHS GP (family doctor) as soon as you arrive — before you need medical help.",
    stage: "D7",
    category: "Health",
    priority: "Very High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "GP registration is free and gives you access to the full NHS. Without registering, you cannot book appointments, get prescriptions, or access hospital referrals when you need them. Some GP surgeries have long waiting lists — register early to avoid being without a doctor.",
    whatToPrepare: [
      "Your UK address",
      "NHS number (if you have one already — check your BRP letter)",
      "Proof of address (tenancy agreement, utility bill, or bank statement)",
    ],
    stepsToTake: [
      "Search for NHS GP surgeries near your accommodation: nhs.uk/service-search/find-a-gp",
      "Call or visit your top choices to check they are accepting new patients.",
      "Fill in a GMS1 registration form (available from the GP surgery or online).",
      "Provide your UK address and student status — you do not need proof of identity for NHS GP registration.",
      "Ask for your NHS number when you register.",
    ],
    commonMistakes: [
      "Waiting until you are ill to try to register — you cannot always register as an emergency patient.",
      "Assuming registration is automatic — you must actively register with a specific GP surgery.",
      "Registering with a GP far from your accommodation — you need to be able to visit when ill.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "NHS GP registration: nhs.uk/nhs-services/gps/how-to-register-with-a-gp | NHS number: nhs.uk/nhs-services/nhs-number",
  },
  {
    taskId: "STU_D7_004",
    title: "Get your NHS number and understand NHS services",
    summary: "Learn how the NHS works and find your NHS number so you can access healthcare correctly.",
    stage: "D7",
    category: "Health",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "The NHS is the UK's public health service. As an international student, you have already paid the Immigration Health Surcharge as part of your visa fee — you are entitled to full NHS care. Understanding how to use it correctly means faster, free treatment when you need it.",
    whatToPrepare: ["Your NHS number (ask your GP when you register)", "Internet access to nhs.uk"],
    stepsToTake: [
      "Register with a GP to get your NHS number assigned (it will be posted to you).",
      "If you already know your NHS number (from previous UK stays or your BRP letter), note it in your phone.",
      "Read the NHS services guide at nhs.uk to understand: when to use 111, when to use 999, when to visit a pharmacy, and when to use A&E.",
      "Download the NHS App — it lets you order prescriptions, book appointments, and view your health records.",
    ],
    commonMistakes: [
      "Going to A&E for non-emergencies — this puts pressure on emergency services and costs the NHS.",
      "Not knowing the difference between 111 (medical help, not 999-level emergencies) and 999.",
      "Paying for private healthcare unnecessarily — most things are free on the NHS.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "NHS 111 (non-emergency medical help): dial 111 | A&E and 999 (emergencies only) | NHS App: nhs.uk/nhs-app",
  },
  {
    taskId: "STU_D7_005",
    title: "Activate student oyster or apply for a transport discount card",
    summary: "Get a student travel card to save money on public transport in London or your city.",
    stage: "D7",
    category: "Transport",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Student oyster cards (London) and railcards (national) give 30–50% off public transport. Without a student discount card, you pay full price — which adds up quickly over a year of commuting.",
    whatToPrepare: [
      "Student ID card",
      "Passport photo (for 18+ Student Oyster photocard)",
      "Bank card to pay the administration fee (usually around £20 for 5 years)",
    ],
    stepsToTake: [
      "If in London: apply for an 18+ Student Oyster photocard at tfl.gov.uk — this gives 30% off bus and tube travel.",
      "If outside London: apply for a 16–25 Railcard (saves 1/3 on all UK train tickets) at 16-25railcard.co.uk.",
      "Save your oyster or railcard details in your phone wallet.",
      "Check if your university offers a free or subsidised travel pass — many do.",
    ],
    commonMistakes: [
      "Not activating the oyster card with your student status — the discount only applies once you are registered as a student.",
      "Not carrying the railcard when travelling — conductors can charge full price + a penalty fare without it.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "18+ Student Oyster: tfl.gov.uk/18plus | 16–25 Railcard: 16-25railcard.co.uk | Uniday: uniday.co.uk (some retailers accept this for discounts without a railcard)",
  },
  {
    taskId: "STU_D7_006",
    title: "Understand council tax and student exemption",
    summary: "Learn what council tax is, why students are exempt, and how to claim the exemption.",
    stage: "D7",
    category: "Local Admin",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 25,
    whyItMatters:
      "Council tax is a mandatory local tax on residential properties in England, Wales, and Scotland — typically £100–£200 per month. Full-time students are exempt. If you do not claim the exemption, the bill goes to your landlord — who may pass it on to you.",
    whatToPrepare: [
      "Proof of student status (student ID card or a letter from your university)",
      "Your tenancy agreement",
      "Your accommodation address",
    ],
    stepsToTake: [
      "Contact your local council (check your address on gov.uk/find-your-local-council).",
      "Tell them you are a full-time student and request a council tax exemption certificate.",
      "If the property is in your name or your landlord bills you, submit the student exemption form.",
      "Keep copies of all correspondence.",
      "If you are billed in error, write to the council with your student status letter.",
    ],
    commonMistakes: [
      "Ignoring council tax bills — even as a student you can receive penalties for non-payment.",
      "Not knowing which council to contact — it is based on your UK address, not your university.",
      "Assuming your landlord will handle it — they may not know you are a student.",
    ],
    riskWarning:
      "Council tax is a legal obligation. If you receive a bill, do not ignore it even if you believe you are exempt — always respond in writing.",
    sourceSignpost:
      "gov.uk/council-tax | Check if you qualify as a full-time student: gov.uk/guidance/council-tax-discounts#full-time-students",
  },
  {
    taskId: "STU_D7_007",
    title: "Join student societies and find local communities",
    summary: "Start building your social and professional network in the UK through your university's student societies.",
    stage: "D7",
    category: "Growth",
    priority: "Low",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "Settling in a new country is not just about admin tasks — your mental health and long-term success benefit from community. Societies are the fastest way to find people with shared interests and build a support network.",
    whatToPrepare: ["Your student ID card", "An open mind"],
    stepsToTake: [
      "Visit your Students' Union website and browse the list of societies.",
      "Attend Freshers' Fair (or equivalent) and sign up for anything that interests you.",
      "Look for international student societies — they understand the specific challenges you are facing.",
      "Join at least one academic society and one social or hobby society.",
      "Save society contact details and WhatsApp or social media group links.",
    ],
    commonMistakes: [
      "Signing up to too many societies and not following through on any.",
      "Only socialising with people from your home country — while comforting, it slows integration and network building.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Your university's Students' Union website is the official source for all societies.",
  },
  {
    taskId: "STU_D7_008",
    title: "First food shop — understand UK supermarkets",
    summary: "Learn how to shop affordably in the UK by understanding the supermarket landscape.",
    stage: "D7",
    category: "Local Life",
    priority: "Low",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Food is one of the biggest monthly expenses for students. Understanding which shops are cheapest, when to buy what, and how to cook simple meals can save you hundreds of pounds a year.",
    whatToPrepare: ["Your student ID (for discounts)", "A reusable bag (mandatory in England since 2021)"],
    stepsToTake: [
      "Visit Aldi and Lidl — they are the cheapest major supermarkets.",
      "For branded goods, compare prices between Tesco, Sainsbury's, Asda, and Morrisons.",
      "Sign up for supermarket loyalty schemes — Tesco Clubcard, Nectar (Sainsbury's/Argos), and Morrisons More give points that convert to vouchers.",
      "Your student NUS/Totum card gives discount at some retailers — activate the app.",
    ],
    commonMistakes: [
      "Shopping at Marks & Spencer or Waitrose every day — these are significantly more expensive.",
      "Not comparing prices — the difference between cheapest and most expensive supermarkets is 30–40% for the same items.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "MoneySavingExpert food shopping guide: moneysavingexpert.com | Which? Best Buy supermarkets: which.co.uk",
  },
  {
    taskId: "STU_D7_009",
    title: "Set up utilities if renting privately",
    summary: "If you are in private rented accommodation, set up your gas, electricity, and internet accounts correctly.",
    stage: "D7",
    category: "Accommodation",
    priority: "Medium",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    conditional: "Only if you are renting privately and the utilities are not included in your rent",
    whyItMatters:
      "If you are responsible for your own utility bills and you do not set up accounts in your name, the bills go to the previous tenant — and debt can follow a property, not a person. You could also be left without energy or internet.",
    whatToPrepare: [
      "Your tenancy agreement (to check what is included in rent)",
      "Your move-in date and meter readings",
      "Your UK bank account (needed to set up direct debits)",
    ],
    stepsToTake: [
      "Check your tenancy agreement — does rent include utilities or not?",
      "If not included: contact the energy supplier for your area and set up an account in your name.",
      "Take photos of your gas and electricity meter readings on move-in day.",
      "Set up accounts with your chosen energy supplier — compare tariffs at uswitch.com.",
      "Arrange internet: Virgin Media, BT, Sky, and TalkTalk are common providers. Check what infrastructure is available at your address.",
    ],
    commonMistakes: [
      "Not reading meter readings on move-in day — you will be billed for the previous tenant's usage.",
      "Staying with the default energy supplier — always compare and switch.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Ofgem (energy regulator): ofgem.gov.uk | Uswitch (comparisons): uswitch.com | Citizens Advice: citizensadvice.org.uk",
  },
  {
    taskId: "STU_D7_010",
    title: "Check your tenancy deposit protection scheme",
    summary: "Confirm that your tenancy deposit is legally protected in a government-approved scheme.",
    stage: "D7",
    category: "Accommodation",
    priority: "High",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 15,
    conditional: "Only if you paid a tenancy deposit",
    whyItMatters:
      "If your deposit is not protected in a government-approved scheme, your landlord is breaking the law and you can take them to court. This takes five minutes to check — and protects your money.",
    whatToPrepare: ["Your deposit amount and date paid", "Your tenancy agreement"],
    stepsToTake: [
      "Check which deposit protection scheme your landlord used: TDS (tenancydepositscheme.com), DPS (depositprotection.com), or MyDeposits (mydeposits.co.uk).",
      "Your landlord must protect your deposit within 30 days of receiving it — if they have not, they owe you compensation.",
      "Log in to the scheme portal to check the amount and details are correct.",
      "Save the certificate and scheme contact details.",
    ],
    commonMistakes: [
      "Not checking — many students do not know their deposit is unprotected until they try to claim it back.",
      "Assuming your landlord will handle it correctly — they are legally required to protect it but not all do.",
    ],
    riskWarning:
      "If your deposit was not protected within 30 days, contact Shelter or a student housing advice service immediately.",
    sourceSignpost:
      "TDS: tenancydepositscheme.com | DPS: depositprotection.com | MyDeposits: mydeposits.co.uk | Shelter: shelterengland.org",
  },

  // ─── FIRST MONTH ────────────────────────────────────────────────────────────
  {
    taskId: "STU_D30_001",
    title: "Open a UK student bank account",
    summary: "Open a dedicated UK student bank account as soon as possible — ideally within your first week.",
    stage: "D30",
    category: "Money",
    priority: "Very High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 45,
    whyItMatters:
      "A UK student bank account gives you a UK sort code and account number — essential for paying rent, receiving wages from part-time work, and proving your UK address to other services. Many accounts also offer an interest-free overdraft, which is useful as a safety net.",
    whatToPrepare: [
      "Passport or UK driving licence",
      "BRP",
      "Proof of UK address (tenancy agreement, accommodation letter, or recent utility bill)",
      "Proof of student status (university letter or student ID)",
    ],
    stepsToTake: [
      "Compare student bank accounts — use moneysavingexpert.com for a full comparison.",
      "Visit your chosen bank's branch or apply online.",
      "Bring all required documents — missing one means a second trip.",
      "Set up online and mobile banking so you can manage your account remotely.",
      "Order a debit card if one does not arrive automatically.",
    ],
    commonMistakes: [
      "Opening an account with a bank that has no nearby branches.",
      "Not checking the overdraft terms — some banks charge interest on the overdraft from day one.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "MSE Student Bank Account Guide: moneysavingexpert.com | FCA (financial regulator): fca.org.uk",
  },
  {
    taskId: "STU_D30_002",
    title: "Register with your GP and book a new patient health check",
    summary: "Confirm GP registration is complete and book a new patient health check if offered.",
    stage: "D30",
    category: "Health",
    priority: "Very High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Many GP surgeries offer a free new patient health check when you register. This is a baseline health assessment that can catch issues early. It also confirms you are properly registered in the NHS system.",
    whatToPrepare: [
      "Your NHS number (if received after GP registration)",
      "A list of any current medications or health conditions",
      "Your medical history summary (conditions, allergies, previous treatments)",
    ],
    stepsToTake: [
      "Call or visit your GP surgery to confirm your registration is complete.",
      "Ask if they offer a new patient health check and book one.",
      "Bring any medical records or summaries you have from your home country.",
      "Tell the GP about any ongoing conditions, medications, or mental health concerns.",
    ],
    commonMistakes: [
      "Registering but never visiting — the health check is a chance to establish yourself with the practice.",
      "Not disclosing mental health concerns — these are treated with the same confidentiality as physical health.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "NHS: nhs.uk | Find a GP: nhs.uk/service-search/find-a-gp",
  },
  {
    taskId: "STU_D30_003",
    title: "Apply for a National Insurance number if planning to work",
    summary: "If you plan to do any paid work in the UK, apply for your National Insurance number now.",
    stage: "D30",
    category: "Work",
    priority: "High",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 25,
    conditional: "Only if you plan to work in the UK",
    whyItMatters:
      "Your National Insurance (NI) number is your unique tax reference number in the UK. You legally need it to work — employers use it to deduct the correct tax and National Insurance contributions from your wages. Without one, you could be taxed incorrectly or miss out on state pension contributions.",
    whatToPrepare: [
      "Proof of the right to work in the UK (passport and BRP)",
      "Proof of address",
      "Proof of student status",
    ],
    stepsToTake: [
      "If you have a pre-existing NI number (from a previous UK stay), note it in your records.",
      "If you do not: call the DWP NI number helpline on 0300 200 3500 to apply.",
      "DWP will schedule an evidence interview — bring your passport and BRP.",
      "Your NI number will be posted to you within 3–4 weeks of the interview.",
      "Once received, save it securely — you will need it for every job.",
    ],
    commonMistakes: [
      "Starting work without an NI number — employers can still hire you but you must get one quickly after starting.",
      "Losing the letter — NI numbers are posted only once. If lost, you need to request a replacement from HMRC.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "HMRC NI number application: gov.uk/apply-national-insurance-number | DWP: dwp.gov.uk",
  },
  {
    taskId: "STU_D30_004",
    title: "Set up your first month's budget and start tracking spending",
    summary: "Create a monthly budget for the first month so you understand where your money goes.",
    stage: "D30",
    category: "Money",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "International students often underestimate living costs in the UK, especially in London. Creating a budget in month one means you can adjust your spending before you run into financial difficulty — not after.",
    whatToPrepare: [
      "Your bank statement (from your UK account)",
      "Your rent amount and due date",
      "Your expected income (student loan, family support, part-time work)",
    ],
    stepsToTake: [
      "List all your fixed monthly costs: rent, utilities (if not included), phone, transport.",
      "Estimate your variable costs: food, social, study materials.",
      "Use a free budgeting app (PensionBee, Emma, or Money Dashboard) to track spending automatically.",
      "Set a weekly food and social spending limit.",
      "Review your actual spending at the end of month one and adjust your budget.",
    ],
    commonMistakes: [
      "Not accounting for one-off setup costs in month one — internet installation, bedding, kitchenware.",
      "Underestimating food costs — cooking at home is much cheaper than eating out or getting takeaway.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "MSE Budget Planner: moneysavingexpert.com/banking/budget-planner | Money Helper: moneyhelper.org.uk",
  },
  {
    taskId: "STU_D30_005",
    title: "Get your student status letter from the university",
    summary: "Request an official student status letter from your university for bank account opening and other services.",
    stage: "D30",
    category: "University",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 15,
    whyItMatters:
      "Banks, letting agents, visa applications, and government agencies often require an official letter confirming you are a full-time student. Getting this early means you have it ready when you need it — rather than rushing to get it before a deadline.",
    whatToPrepare: ["Your student ID number", "The reason you need the letter"],
    stepsToTake: [
      "Check your university student portal to see if you can download a student status letter automatically.",
      "If not available online: request one from your university's student services or registry.",
      "Specify exactly what the letter needs to say — some banks have specific requirements.",
      "Most universities issue these within 3–5 working days. Some charge a small fee.",
      "Request 2–3 copies at once so you do not need to request again soon.",
    ],
    commonMistakes: [
      "Requesting one letter at a time — always request spares.",
      "Not specifying the exact purpose — some agencies need specific wording.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Your university's student services or registry office is the issuing body. Contact them via the official university website.",
  },
  {
    taskId: "STU_D30_006",
    title: "Understand your right to work and part-time work conditions",
    summary: "Know the rules around working while studying in the UK — hours limits, visa conditions, and your rights.",
    stage: "D30",
    category: "Work",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 25,
    whyItMatters:
      "Your student visa has specific work conditions. Working more than you are allowed to can breach your visa conditions and risk your studies. At the same time, part-time work is a valuable part of the UK student experience — understanding your rights means you can work confidently and safely.",
    whatToPrepare: [
      "Your BRP or visa vignette (to check your work conditions)",
      "Internet access to check Home Office guidance",
    ],
    stepsToTake: [
      "Check your BRP or visa vignette for your work conditions — the standard student visa allows up to 20 hours per week during term time.",
      "Visit gov.uk/student-visa/work for the official guidance.",
      "Know your rights: you are entitled to National Minimum Wage, sick pay, and holiday pay from day one of any job.",
      "If your employer does not follow employment law, contact the Advisory, Conciliation and Arbitration Service (Acas).",
    ],
    commonMistakes: [
      "Working more than the allowed hours — this can affect your visa status.",
      "Accepting cash-in-hand jobs — these are illegal and leave you without employment protections.",
    ],
    riskWarning:
      "If you are working in the UK illegally (over-hours or cash-in-hand), you have no employment rights, no tax contributions recorded, and risk your visa. Always work legally.",
    sourceSignpost:
      "Home Office student visa work conditions: gov.uk/student-visa/work | Acas (employment advice): acas.org.uk | National Minimum Wage: gov.uk/national-minimum-wage",
  },
  {
    taskId: "STU_D30_007",
    title: "Review your housing contract and understand your tenant rights",
    summary: "Read your tenancy agreement carefully and understand what rights and obligations you have as a tenant.",
    stage: "D30",
    category: "Accommodation",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 45,
    whyItMatters:
      "Your tenancy agreement is a legally binding contract. Not understanding it means you could miss clauses that cost you money, restrict your rights, or expose you to unexpected obligations — like repair costs, early termination fees, or unwanted clauses about guests or noise.",
    whatToPrepare: ["Your tenancy agreement", "Internet access for guidance"],
    stepsToTake: [
      "Read the entire tenancy agreement — do not sign anything you have not read.",
      "Check: What is the minimum tenancy length? What is the notice period? What deposits and fees apply?",
      "Use Shelter's tenancy agreement checker: shelterengland.org.",
      "If anything is unclear, contact your university's student housing advice service.",
      "Save a copy of the signed agreement in your cloud storage.",
    ],
    commonMistakes: [
      "Not reading the small print — the most important terms are often buried in clauses.",
      "Assuming the letting agent or landlord explained everything — always read it yourself.",
    ],
    riskWarning:
      "Breaking a tenancy early can result in financial penalties. Make sure you understand the exit terms before signing.",
    sourceSignpost:
      "Shelter England: shelterengland.org | Citizens Advice: citizensadvice.org.uk | Tenant Fees Act guidance: gov.uk/guidance/tenant-fees-act",
  },
  {
    taskId: "STU_D30_008",
    title: "Set up your council tax account and confirm student exemption",
    summary: "Contact your local council, confirm your student exemption, and set up a council tax account.",
    stage: "D30",
    category: "Local Admin",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Council tax is a real legal obligation. Even as a student, you need to actively claim the exemption — if you do not, the council will assume you are a liable resident and send you a bill. Resolving an erroneous bill takes time and paperwork.",
    whatToPrepare: [
      "Your UK address",
      "Proof of student status letter",
      "Your tenancy agreement",
    ],
    stepsToTake: [
      "Go to gov.uk/find-your-local-council and find your council's website.",
      "Search for 'student council tax exemption' and follow their process.",
      "Submit your student status letter and tenancy agreement.",
      "Get written confirmation that your exemption has been applied.",
      "Set a calendar reminder to re-apply each year if your course continues.",
    ],
    commonMistakes: [
      "Assuming you are automatically exempt — you must apply.",
      "Ignoring letters from the council — always respond, even if just to confirm your student status.",
    ],
    riskWarning:
      "Unpaid council tax can result in court action and bailiff visits. Always respond to any correspondence.",
    sourceSignpost:
      "gov.uk/council-tax | Citizens Advice: citizensadvice.org.uk",
  },
  {
    taskId: "STU_D30_009",
    title: "Build a UK CV and learn to spot job scams",
    summary: "Create a UK-format CV and understand the common job scam warning signs.",
    stage: "D30",
    category: "Work",
    priority: "Medium",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 45,
    whyItMatters:
      "UK CVs are different from CVs in other countries. A poorly formatted CV in the wrong style will be rejected by UK employers. Equally, job scams targeting international students are common — knowing the warning signs keeps you safe.",
    whatToPrepare: [
      "Your education history (from primary school onwards — UK CVs usually include this)",
      "Your work experience",
      "Your passport (for right-to-work checks — you will need to prove this legally)",
    ],
    stepsToTake: [
      "Use a free CV template from Indeed, Totaljobs, or the University Careers Service.",
      "UK CV format: personal profile, education, work experience, skills, references.",
      "Get your CV reviewed by your university careers service — it is free for students.",
      "Learn the job scam warning signs: job scams guide in the NewStart UK guidance library.",
      "Never pay money to get a job — legitimate employers do not charge application fees.",
    ],
    commonMistakes: [
      "Including a photo or personal details (age, marital status) — this is not standard in the UK and can cause bias.",
      "Applying for jobs that ask for payment — this is always a scam.",
    ],
    riskWarning:
      "Job scams targeting international students are common. If an offer seems too good to be true, it is. See the Job Scam Warning guide.",
    sourceSignpost:
      "Indeed CV templates: indeed.com | Totaljobs CV help: totaljobs.com | Action Fraud (scam reporting): actionfraud.police.uk",
  },
  {
    taskId: "STU_D30_010",
    title: "Explore UK healthcare extras — dentist, optician, pharmacy",
    summary: "Find a dentist, optician, and pharmacy near your accommodation for ongoing health needs.",
    stage: "D30",
    category: "Health",
    priority: "Medium",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "The NHS covers GP visits and hospital care. But dental, optical, and prescription costs are separate — and can be expensive if you need them unexpectedly. Registering with these services now means you are not scrambling when you have toothache or need new glasses.",
    whatToPrepare: ["Your NHS number", "Your UK address"],
    stepsToTake: [
      "Find an NHS dentist near you: nhs.uk/service-search/find-an-nhs-dentist — note that NHS places are limited, so register quickly.",
      "Find a pharmacy near you for prescriptions and minor health advice.",
      "Find an optician for eye tests — students are entitled to a free NHS eye test and may qualify for a voucher toward glasses.",
      "NHS prescriptions cost £9.90 per item (as of 2024) — check if you qualify for free prescriptions (students on a low income can apply for an HC2 certificate).",
    ],
    commonMistakes: [
      "Not registering with a dentist early — NHS dental places are in high demand.",
      "Not knowing that prescriptions are not free unless you qualify for an HC2 or are under 19 in full-time education.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "NHS dentist finder: nhs.uk/service-search/find-an-nhs-dentist | HC2 certificate (free prescriptions): nhs.uk/healthcosts | Optician finder: nhs.uk/service-search/find-an-optician",
  },

  // ─── DAYS 31–90 ─────────────────────────────────────────────────────────────
  {
    taskId: "STU_D90_001",
    title: "Review your first month budget and adjust",
    summary: "Look at what you actually spent in your first month and adjust your budget accordingly.",
    stage: "D90",
    category: "Money",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "Month one almost always includes one-off setup costs — bedding, kitchenware, internet installation. By month two, your spending pattern will be different. Reviewing and adjusting your budget means you can spot problems early.",
    whatToPrepare: [
      "Your bank statements for the first month",
      "Your original budget",
      "Your actual spending totals",
    ],
    stepsToTake: [
      "Open your bank app and categorise your spending for the month.",
      "Compare actual spending vs. your planned budget.",
      "Adjust your budget categories for months 2 and 3.",
      "Look for one area where you can cut costs if you are overspending.",
      "Set a monthly spending review routine for every month going forward.",
    ],
    commonMistakes: [
      "Not reviewing your budget at all — financial stress is common among students who do not track spending.",
      "Being too strict — a small social budget is important for mental health.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "MSE Budget Planner: moneysavingexpert.com/banking/budget-planner",
  },
  {
    taskId: "STU_D90_002",
    title: "Check your UK banking is working well",
    summary: "Confirm your UK bank account is fully functional for receiving wages and paying bills.",
    stage: "D90",
    category: "Money",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 15,
    whyItMatters:
      "If your bank account has issues — failed standing orders, card not working, incorrect details — fixing them quickly is important. This becomes critical if you start part-time work and need your wages paid in.",
    whatToPrepare: ["Your UK bank account details", "Your online banking app"],
    stepsToTake: [
      "Check your bank app to confirm: account number, sort code, and address are correct.",
      "Test that your card works at a shop and ATM.",
      "Confirm that your overdraft limit (if applicable) is as expected.",
      "Set up mobile banking notifications so you see all transactions in real time.",
      "If you have had any issues, visit a branch or call customer services.",
    ],
    commonMistakes: [
      "Not checking your bank account regularly — fraud and errors are easier to resolve when caught early.",
      "Overdraft use without a plan — interest-free overdrafts for students have limits.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "FCA (Financial Conduct Authority): fca.org.uk | Report bank fraud: actionfraud.police.uk",
  },
  {
    taskId: "STU_D90_003",
    title: "Review your housing — is it stable and working for you?",
    summary: "Check whether your accommodation is meeting your needs and whether you need to take any action.",
    stage: "D90",
    category: "Accommodation",
    priority: "Medium",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "After 30 days in your accommodation, you will have a clear sense of whether it works for you. If there are ongoing issues — damp, repairs, landlord disputes — the earlier you address them, the more options you have.",
    whatToPrepare: [
      "Your tenancy agreement",
      "A list of any outstanding issues with your accommodation",
      "Knowledge of your rights",
    ],
    stepsToTake: [
      "Review: Is the accommodation what you expected? Are there issues you have been ignoring?",
      "If there are unresolved issues, write to your landlord in writing (email counts) to formally notify them.",
      "Check: Is your deposit protected? Has it been correctly accounted for?",
      "Check: Are you happy with the neighbourhood and transport links?",
      "If you are considering moving, check your notice period and any costs in your tenancy agreement.",
    ],
    commonMistakes: [
      "Putting off dealing with landlord issues — small problems become big problems.",
      "Not keeping written records of all communication with your landlord.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Shelter England: shelterengland.org | Tenant Rights: citizensadvice.org.uk/tenancy-rights",
  },
  {
    taskId: "STU_D90_004",
    title: "Update your university with any change of address",
    summary: "Tell your university your UK address if you have not already, or update it if you have moved.",
    stage: "D90",
    category: "University",
    priority: "High",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 10,
    whyItMatters:
      "Your university uses your address for all official correspondence — exam results, graduation invites, student finance letters. If they do not have your correct address, important post may not reach you.",
    whatToPrepare: ["Your current UK address", "Student portal login"],
    stepsToTake: [
      "Log into your student portal and check your registered address.",
      "Update it if it is incorrect or missing.",
      "If you move during your course, update your address immediately.",
    ],
    commonMistakes: [
      "Not updating the address after moving — missing important post.",
      "Assuming the university knows your accommodation address from your visa — they often do not.",
    ],
    riskWarning: undefined,
    sourceSignpost: undefined,
  },
  {
    taskId: "STU_D90_005",
    title: "Explore part-time work or internship opportunities",
    summary: "After your settling-in period, start looking at part-time work or internships relevant to your career.",
    stage: "D90",
    category: "Work",
    priority: "Medium",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 60,
    whyItMatters:
      "Part-time work in your field — not just retail or hospitality — builds your CV, expands your UK professional network, and makes you more competitive after graduation. Start exploring options by the end of month two.",
    whatToPrepare: [
      "Your updated UK-format CV",
      "An understanding of your visa work-hour limits",
      "Your LinkedIn profile (set this up if you have not already)",
    ],
    stepsToTake: [
      "Visit your university careers service — they have exclusive job listings and fairs.",
      "Search on LinkedIn and Indeed for part-time roles or internships in your field.",
      "Attend any careers fairs at your university.",
      "Check your visa conditions before applying — confirm the hours you can work.",
      "Apply to at least 2–3 relevant part-time roles or internships.",
    ],
    commonMistakes: [
      "Only looking at bar and restaurant work — this pays but does not build your career.",
      "Overworking — keep your studies as your priority.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "Your university careers service website | LinkedIn: linkedin.com | Indeed: indeed.co.uk | RateMyPlacement (internships): ratemmyplacement.co.uk",
  },
  {
    taskId: "STU_D90_006",
    title: "Conduct your 90-day settlement review",
    summary: "Reflect on your first 90 days — what is going well, what is not, and what you need to fix.",
    stage: "D90",
    category: "Growth",
    priority: "Low",
    required: true,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 30,
    whyItMatters:
      "The first 90 days of any new life chapter are intense. Taking 30 minutes to write down what is working and what is not helps you see your situation clearly and make intentional adjustments — rather than drifting.",
    whatToPrepare: [
      "Your original reasons for coming to the UK",
      "Your checklist progress",
      "A blank notebook or document",
    ],
    stepsToTake: [
      "Answer: What have been my three biggest achievements in the last 90 days?",
      "Answer: What is still causing me stress or uncertainty?",
      "Answer: What admin tasks are still incomplete? (Go to your checklist and check.)",
      "Answer: Who are my three most important connections in the UK now?",
      "Answer: What do I want to achieve in the next 90 days?",
      "Share your review with someone you trust — a family member, friend, or mentor.",
    ],
    commonMistakes: [
      "Only focusing on what is going wrong — celebrate what you have achieved.",
      "Not updating your checklist — by now many tasks should be marked complete.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "NewStart UK 90-Day Review guidance: newstartuk.app/guides/90-day-review",
  },
  {
    taskId: "STU_D90_007",
    title: "Understand UK healthcare extras — dentist, eye test, and prescriptions",
    summary: "Confirm you have access to dental, optical, and pharmacy services.",
    stage: "D90",
    category: "Health",
    priority: "Low",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Healthcare gaps — untreated dental problems, expired glasses prescriptions, or prescription costs — become expensive when they become urgent. By 90 days, you should have these basics in place.",
    whatToPrepare: ["Your NHS number", "Your UK address"],
    stepsToTake: [
      "Confirm you are registered with an NHS dentist.",
      "Book a free NHS eye test if you have not had one.",
      "Check whether you qualify for an HC2 certificate for free prescriptions.",
      "Know where your nearest pharmacy is for minor health issues and prescription collections.",
    ],
    commonMistakes: [
      "Waiting until you have toothache to find a dentist — NHS dental places are limited.",
      "Not applying for an HC2 certificate — students on a low income can get free prescriptions and eye tests.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "HC2 certificate: nhs.uk/healthcosts | NHS dentist finder: nhs.uk/service-search/find-an-nhs-dentist",
  },
  {
    taskId: "STU_D90_008",
    title: "Plan for long-term finances — consider opening a savings account",
    summary: "Look at your finances after 90 days and consider whether a savings account makes sense.",
    stage: "D90",
    category: "Money",
    priority: "Low",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 20,
    whyItMatters:
      "Once you have a UK bank account and a month or two of income and expenditure tracked, you can make informed decisions about savings. Even small amounts saved regularly build good financial habits.",
    whatToPrepare: [
      "Your monthly budget",
      "Any savings goal (emergency fund, travel, post-graduation)",
    ],
    stepsToTake: [
      "Check if your current bank offers a savings account — most student accounts do not, so you may need a separate account.",
      "Compare savings accounts at different banks and with apps like Chip, Plum, or Wealthify.",
      "Consider a regular savings account — even £20–£50 per month builds up.",
      "Do not lock money in a long-term savings account you might need access to.",
    ],
    commonMistakes: [
      "Trying to save too much — your priority in months 1–3 is covering costs and building good habits.",
      "Ignoring student loan interest — this accumulates while you study but you do not repay until you earn above the threshold.",
    ],
    riskWarning:
      "Never invest in anything you do not fully understand. Cryptocurrency, forex trading, and 'guaranteed returns' schemes are high-risk. If in doubt, speak to your university's money advice service.",
    sourceSignpost:
      "MSE Savings guide: moneysavingexpert.com/savings | Student Loan repayment: gov.uk/repaying-student-loan",
  },
  {
    taskId: "STU_D90_009",
    title: "Build your professional network — careers service and LinkedIn",
    summary: "Start building your UK professional network while you are settled in.",
    stage: "D90",
    category: "Growth",
    priority: "Low",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 45,
    whyItMatters:
      "The UK job market is relationship-driven. Companies hire through referrals and networks as much as through job postings. Starting to build your network while you are a student — not after you graduate — gives you a significant advantage.",
    whatToPrepare: [
      "Your updated CV",
      "A LinkedIn profile (linkedin.com)",
      "Your university careers service login",
    ],
    stepsToTake: [
      "Set up a professional LinkedIn profile with your photo, education, and current course.",
      "Connect with your course lecturers, careers advisors, and fellow students.",
      "Connect with alumni from your university who work in your field.",
      "Attend at least one industry event or careers fair.",
      "Follow companies you are interested in on LinkedIn.",
    ],
    commonMistakes: [
      "Only connecting with people from your home country — diverse networks open more doors.",
      "Not engaging with content on LinkedIn — liking and commenting on posts increases your visibility.",
    ],
    riskWarning: undefined,
    sourceSignpost:
      "LinkedIn: linkedin.com | Your university careers service (exclusive access for students) | LinkedIn Learning: linkedin.com/learning (free with student account)",
  },
  {
    taskId: "STU_D90_010",
    title: "Update family on your settlement progress",
    summary: "Share a structured update with family on how your first 90 days have gone.",
    stage: "D90",
    category: "Growth",
    priority: "Low",
    required: false,
    active: true,
    aiHelperAllowed: true,
    estimatedMinutes: 15,
    whyItMatters:
      "Family members are often worried but do not want to pressure you. A proactive, honest update — covering what is going well, what is hard, and what you need — reduces their anxiety and builds a support relationship based on real information.",
    whatToPrepare: [
      "Your 90-day reflection notes",
      "Any specific questions or requests you want to raise",
    ],
    stepsToTake: [
      "Write a structured update covering: what you have achieved, what you have found difficult, what you need from them.",
      "Share your checklist progress (or at least the headline numbers).",
      "Be honest about any concerns — family support is most useful when they know the real picture.",
      "Set a regular update schedule — monthly updates are easier to maintain than ad-hoc ones.",
    ],
    commonMistakes: [
      "Only sharing the good news — families who only hear positive updates can be shocked when difficulties emerge later.",
      "Not asking for help when you need it — families usually want to help but do not know how.",
    ],
    riskWarning: undefined,
    sourceSignpost: undefined,
  },
];
