import type { ChecklistTask } from "@/types";

export const SEED_TASKS: ChecklistTask[] = [
  // ── PRE-ARRIVAL ──────────────────────────────────────────────────────────
  {
    taskId: "STU_PRE_001",
    title: "Confirm your university enrolment and arrival instructions",
    stage: "PRE",
    category: "University",
    priority: "High",
    required: true,
    dependencyIds: [],
    whyItMatters:
      "Your university needs to confirm you before you can complete any other student steps — including getting your student ID, accessing accommodation, and opening a bank account.",
    whatToPrepare: [
      "Your offer letter or CAS number",
      "Passport and visa details",
      "Contact details for your university international office",
    ],
    stepsToTake: [
      "Log into your university applicant portal and confirm your place.",
      "Download or screenshot your CAS (Confirmation of Acceptance for Studies) statement.",
      "Note the deadline for university check-in — this is usually within a few days of arrival.",
      "Find the international student office contact details and save them somewhere safe.",
      "Register for your university orientation programme.",
    ],
    commonMistakes: [
      "Missing the check-in deadline — some universities cancel your place after a certain date.",
      "Not downloading the CAS before arriving — you will need it for bank accounts and the NHS.",
      "Arriving without knowing where to go for university enrolment on campus.",
    ],
    riskWarning: "If you miss the university check-in deadline, your place may be cancelled and your student visa status could be affected.",
    guidanceSlug: "student-status-letter",
    sourceNote: "GOV.UK CAS guidance · Your university's international student pages",
    reminderTrigger: "7 days before arrival",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_PRE_002",
    title: "Confirm your accommodation and plan your first night",
    stage: "PRE",
    category: "Accommodation",
    priority: "High",
    required: true,
    dependencyIds: ["STU_PRE_001"],
    whyItMatters:
      "You need somewhere safe and confirmed to go when you land. Arriving without accommodation sorted is stressful and expensive.",
    whatToPrepare: [
      "Your accommodation booking confirmation or contract",
      "Address in the UK",
      "Emergency contact details for your landlord or university accommodation office",
      "Directions from the airport to your accommodation",
    ],
    stepsToTake: [
      "Confirm your accommodation booking and get the full UK address.",
      "Save your landlord's or university's emergency contact number to your phone.",
      "Print or save your accommodation confirmation to show at check-in.",
      "Plan your route from the airport — book a taxi or note public transport options.",
      "Arrange your first-night stay if your accommodation is not available on arrival day.",
      "If renting privately, check the deposit protection scheme your landlord uses.",
    ],
    commonMistakes: [
      "Arriving at university accommodation outside check-in hours — contact them in advance.",
      "Paying a deposit to a private landlord without seeing a contract first.",
      "Not checking what is included in the rent — bills, internet, etc.",
    ],
    riskWarning: "Never pay a deposit for private accommodation without a written tenancy agreement. See our housing scam warning guide.",
    guidanceSlug: "uk-accommodation-guide",
    sourceNote: "Shelter England · Your university's accommodation service",
    reminderTrigger: "3 days before arrival",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_PRE_003",
    title: "Prepare certified copies of all key documents",
    stage: "PRE",
    category: "Documents",
    priority: "High",
    required: true,
    dependencyIds: [],
    whyItMatters:
      "You will need to show your documents many times in the UK — to universities, banks, landlords, and the NHS. Having organised copies saves time and reduces stress.",
    whatToPrepare: [
      "Passport (valid for the duration of your course)",
      "Visa or entry clearance (Biometric Residence Permit — BRP — if you have one)",
      "CAS statement",
      "University offer letter",
      "Travel insurance certificate",
      "Proof of accommodation",
      "Previous qualifications (certificates/transcripts)",
      "Passport-size photos (UK format — 45mm × 35mm)",
    ],
    stepsToTake: [
      "Check your passport is valid for at least 6 months beyond your planned stay.",
      "Check when your BRP must be collected (usually within 10 days of arrival).",
      "Make certified copies of all documents — ask a solicitor, university, or notary.",
      "Keep digital copies saved securely (not on a device only — cloud or email yourself a copy).",
      "Store originals separately from copies.",
      "Save a list of all document reference numbers somewhere safe.",
    ],
    commonMistakes: [
      "Bringing documents in a bag that will go in the hold — keep originals in your hand luggage.",
      "Not knowing where your BRP will be sent — this is now often via post.",
      "Losing documents and having no copies to replace them quickly.",
    ],
    riskWarning: "Keep your passport and BRP safe at all times. If you lose them, report to the police and Home Office immediately.",
    sourceNote: "GOV.UK · Home Office",
    reminderTrigger: "14 days before arrival",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_PRE_004",
    title: "Plan your airport-to-accommodation route",
    stage: "PRE",
    category: "Transport",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_PRE_002"],
    whyItMatters:
      "Landing in a new country and figuring out transport at the same time is overwhelming. A plan means you arrive calmly rather than stressed.",
    whatToPrepare: [
      "Your accommodation address (saved in your phone and printed)",
      "Airport name and terminal",
      "Public transport options or pre-booked taxi contact",
      "Approximate cost of transport options",
    ],
    stepsToTake: [
      "Find out which London airport or regional airport you are landing at.",
      "Check National Rail or TFL (Transport for London) for train/tube options.",
      "If landing at Heathrow, Gatwick, or Stansted — check if your university runs a free shuttle bus.",
      "Pre-book a taxi if you have a lot of luggage or are arriving late at night.",
      "Download the TfL app or buy an Oyster card (or register for a Student Oyster) before you arrive.",
      "Download offline maps of your city.",
    ],
    commonMistakes: [
      "Not knowing which terminal you are landing at — check your airline's website.",
      "Arriving at a train station with no cash or Oyster card — have a plan for paying.",
      "Missing the last train — check timetables before you travel.",
    ],
    sourceNote: "TFL (Transport for London) · National Rail Enquiries · GOV.UK",
    reminderTrigger: "7 days before arrival",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_PRE_005",
    title: "Sort your money before you travel",
    stage: "PRE",
    category: "Money",
    priority: "High",
    required: true,
    dependencyIds: [],
    whyItMatters:
      "You need funds immediately on arrival — for transport, food, and emergencies. Arriving with no access to money in the UK causes serious problems.",
    whatToPrepare: [
      "A debit or credit card that works internationally (check with your bank before you leave)",
      "Some UK cash (order from your bank before you travel)",
      "An international money transfer service (like Wise or Revolut) set up before arrival",
      "Approximately £200–500 in cash for your first week",
    ],
    stepsToTake: [
      "Call your home bank — tell them you are travelling to the UK and for how long.",
      "Ask about international transaction fees and ATM withdrawal fees.",
      "Consider opening a digital bank account (Monzo, Starling) before you arrive — you can often do this online from your home country.",
      "Order some UK sterling cash from your bank (allow 5–7 working days).",
      "Set up a money transfer app (Wise or Revolut) for better exchange rates when sending money from home.",
      "Do not carry large amounts of cash.",
    ],
    commonMistakes: [
      "Your card gets blocked because your bank thinks it is fraud — call them before you travel.",
      "Paying high international transfer fees — use Wise or Revolut for regular transfers from home.",
      "Arriving with only a credit card and no debit card — some places only accept debit.",
    ],
    sourceNote: "UK Finance · FCA (Financial Conduct Authority)",
    reminderTrigger: "14 days before arrival",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_PRE_006",
    title: "Check your visa and BRP entry clearance details",
    stage: "PRE",
    category: "Documents",
    priority: "High",
    required: true,
    dependencyIds: [],
    whyItMatters:
      "Your visa conditions and entry clearance (BRP) determine your rights in the UK. Understanding them before you arrive prevents costly mistakes.",
    whatToPrepare: [
      "Your passport (with visa vignette)",
      "Your CAS number",
      "Your sponsor's details (university name and licence number)",
    ],
    stepsToTake: [
      "Check your passport has a valid student visa vignette (if you are a non-EEA national).",
      "Note your BRP collection location — this is shown in your decision letter from UKVI.",
      "Know your conditions — including work hour limits if you are on a Student Route visa.",
      "If you have a Student Route visa, you can work up to 20 hours per week during term time.",
      "Check when your visa expires and when your latest date to collect your BRP is.",
    ],
    commonMistakes: [
      "Working more than the permitted hours and risking visa cancellation.",
      "Not collecting the BRP within 10 days of arrival — this is now a legal requirement.",
      "Not informing the university of a change of address within the required timeframe.",
    ],
    riskWarning: "If you breach your visa conditions (including working too many hours), you may face cancellation, deportation, and a ban on returning to the UK.",
    sourceNote: "GOV.UK (UKVI) · UKCISA",
    reminderTrigger: "7 days before arrival",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_PRE_007",
    title: "Research UK phone options — SIM vs eSIM",
    stage: "PRE",
    category: "Local Life",
    priority: "Medium",
    required: false,
    dependencyIds: [],
    whyItMatters:
      "Having a UK phone number quickly after arrival is important for banks, landlords, and your university. Understanding your options before you arrive saves money.",
    whatToPrepare: [
      "Your current phone — is it unlocked and eSIM compatible?",
      "An idea of your data and call needs",
    ],
    stepsToTake: [
      "Check if your current phone is unlocked (you can usually check with your current provider).",
      "Research UK SIM-only plans — giffgaff, Smarty, iD Mobile, and Lebara are popular with students.",
      "Check if your phone supports eSIM — many newer phones do (iPhone XS+, Samsung S20+).",
      "Consider a prepaid SIM for your first 30 days before committing to a monthly plan.",
      "If you will receive calls from home often, check international call rates.",
    ],
    commonMistakes: [
      "Signing a 12-month phone contract before knowing your needs.",
      "Using your home country SIM abroad — roaming charges can be very expensive.",
      "Buying a SIM from an unofficial seller — only buy from registered providers.",
    ],
    guidanceSlug: "sim-esim-guide",
    sourceNote: "Ofcom · Mobile provider websites",
    reminderTrigger: "3 days before arrival",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_PRE_008",
    title: "Notify your university of your arrival plan",
    stage: "PRE",
    category: "University",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_PRE_001"],
    whyItMatters:
      "Universities track student arrivals for welfare purposes. Notifying them helps them support you and confirms you are in the UK safely.",
    whatToPrepare: [
      "Your student ID number",
      "Your expected arrival date",
      "Emergency contact details",
    ],
    stepsToTake: [
      "Email or log into your student portal to notify the university of your arrival date.",
      "Provide an emergency contact name and phone number.",
      "If your university offers airport pick-up, book it early — spaces are limited.",
      "Save the university's out-of-hours emergency number.",
    ],
    commonMistakes: [
      "Not notifying the university until after the deadline.",
      "Not updating them if your arrival date changes.",
    ],
    sourceNote: "Your university's international student pages",
    reminderTrigger: "7 days before arrival",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },

  // ── ARRIVAL DAY ─────────────────────────────────────────────────────────
  {
    taskId: "STU_D1_001",
    title: "Arrive safely and confirm your accommodation access",
    stage: "D1",
    category: "Safety",
    priority: "Very High",
    required: true,
    dependencyIds: ["STU_PRE_002", "STU_PRE_004"],
    whyItMatters:
      "Your personal safety is the first priority. Getting settled securely means everything else can follow.",
    whatToPrepare: [
      "Your accommodation address (printed and saved in phone)",
      "Emergency contact numbers",
      "Enough cash for immediate needs",
    ],
    stepsToTake: [
      "Travel to your accommodation safely.",
      "Contact your landlord or university accommodation office when you arrive.",
      "Get your keys and confirm your room or flat number.",
      "Check that locks on doors and windows are working.",
      "Text or call a family member or friend to confirm you have arrived safely.",
      "Save the emergency services number (999 in the UK) in your phone.",
    ],
    commonMistakes: [
      "Leaving bags unattended at any point during your journey.",
      "Following directions from strangers at the airport without verifying independently.",
      "Arriving at accommodation out-of-hours without the correct contact.",
    ],
    riskWarning: "If anyone at the airport offers to carry your bags, help you find a taxi for a fee, or asks you to follow them — be cautious. Legitimate services have official signs and desks.",
    sourceNote: "Metropolitan Police · Action Fraud",
    reminderTrigger: "arrival_date",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: false,
    sourceRequired: false,
  },
  {
    taskId: "STU_D1_002",
    title: "Tell family or an emergency contact you have arrived safely",
    stage: "D1",
    category: "Safety",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D1_001"],
    whyItMatters:
      "Your family will worry. Confirming you are safe prevents unnecessary worry and creates a record of your safe arrival.",
    whatToPrepare: [
      "Your accommodation address",
      "A way to contact them (WhatsApp, phone, email)",
    ],
    stepsToTake: [
      "Send a message or call as soon as you have Wi-Fi or mobile signal.",
      "Share your accommodation address with your emergency contact.",
      "Share the university's emergency contact number with your family too.",
    ],
    commonMistakes: [
      "Running out of phone battery before messaging — charge before you travel.",
    ],
    sourceNote: "",
    reminderTrigger: "arrival_date",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: false,
    sourceRequired: false,
  },
  {
    taskId: "STU_D1_003",
    title: "Collect keys and check your accommodation condition",
    stage: "D1",
    category: "Accommodation",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D1_001"],
    whyItMatters:
      "Checking your accommodation on the first day means any damage or problems can be documented before you are held responsible for them.",
    whatToPrepare: [
      "Your tenancy agreement",
      "A camera or phone to take photos",
      "A checklist of what should be in the property",
    ],
    stepsToTake: [
      "Walk through every room and check for any existing damage.",
      "Take time-stamped photos of everything — walls, floors, kitchen, bathroom, furniture.",
      "Note any appliances that are not working.",
      "Check that all keys provided match all locks.",
      "Report any damage to your landlord or university accommodation office immediately — in writing.",
    ],
    commonMistakes: [
      "Not documenting existing damage — you could be charged for it when you leave.",
      "Waiting days or weeks to report a maintenance issue — report it immediately.",
      "Not reading the inventory check-in report before signing it.",
    ],
    guidanceSlug: "uk-accommodation-guide",
    sourceNote: "Shelter England",
    reminderTrigger: "arrival_date",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D1_004",
    title: "Photograph and document the condition of your accommodation",
    stage: "D1",
    category: "Accommodation",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_D1_003"],
    whyItMatters:
      "Your deposit is at stake. Thorough photos protect you from being wrongly charged for damage you did not cause.",
    whatToPrepare: [
      "A smartphone with a camera",
      "Enough storage space or cloud backup",
    ],
    stepsToTake: [
      "Photograph every surface — walls, ceilings, floors, doors, windows.",
      "Photograph all appliances, fixtures, and fittings.",
      "Photograph the outside of the building and your front door.",
      "Take wide-angle shots and close-ups.",
      "Save photos with the date and store them somewhere safe (not just on your phone).",
      "Complete and return the landlord's inventory check-in form promptly.",
    ],
    commonMistakes: [
      "Only taking photos of obvious damage — document everything.",
      "Deleting photos before your tenancy ends — keep them for at least 3 months after.",
    ],
    guidanceSlug: "deposit-protection",
    sourceNote: "Shelter England · MyDeposits",
    reminderTrigger: "arrival_date + 1 day",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D1_005",
    title: "Activate your UK phone and set up your SIM or eSIM",
    stage: "D1",
    category: "Local Life",
    priority: "High",
    required: true,
    dependencyIds: ["STU_PRE_007"],
    whyItMatters:
      "A UK phone number is required for bank accounts, university registration, and many other services. Getting this set up early removes a major blocker.",
    whatToPrepare: [
      "Your new SIM card or eSIM activation code",
      "Your phone",
      "Some UK payment method for the top-up or plan",
    ],
    stepsToTake: [
      "Insert your SIM or activate your eSIM using the instructions provided.",
      "Top up or activate your chosen plan.",
      "Test your phone can make and receive calls and texts.",
      "Save important numbers: university accommodation, landlord, emergency services (999).",
      "Download WhatsApp and other useful apps using your Wi-Fi.",
    ],
    commonMistakes: [
      "Running up a large bill before understanding your plan's limits.",
      "Not checking coverage in your area before choosing a provider.",
    ],
    guidanceSlug: "sim-esim-guide",
    sourceNote: "Ofcom",
    reminderTrigger: "arrival_date + 1 day",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D1_006",
    title: "Register with your university — confirm your enrolment in person",
    stage: "D1",
    category: "University",
    priority: "Very High",
    required: true,
    dependencyIds: ["STU_PRE_001"],
    whyItMatters:
      "University registration is required to access your student ID, loan or scholarship payments, library, and academic services. Do this as soon as possible after arrival.",
    whatToPrepare: [
      "Passport",
      "BRP (if collected)",
      "CAS statement",
      "Proof of address (your accommodation confirmation or tenancy agreement)",
    ],
    stepsToTake: [
      "Check your university's registration deadline.",
      "Visit the university in person or complete online registration if available.",
      "Submit all required documents.",
      "Collect your student ID card — you will need this for the library and many discounts.",
      "Activate your university IT account and student email.",
    ],
    commonMistakes: [
      "Missing the registration deadline — follow up immediately if you have any delays.",
      "Not activating your university email — this is the official channel for all university communication.",
    ],
    guidanceSlug: "student-status-letter",
    sourceNote: "Your university's website and international office",
    reminderTrigger: "arrival_date + 2 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },

  // ── FIRST WEEK ────────────────────────────────────────────────────────────
  {
    taskId: "STU_D7_001",
    title: "Complete university check-in and collect your student ID",
    stage: "D7",
    category: "University",
    priority: "Very High",
    required: true,
    dependencyIds: ["STU_D1_006"],
    whyItMatters:
      "Your student ID unlocks student discounts, library access, and proves your student status for banks and employers.",
    whatToPrepare: [
      "Your passport",
      "Your CAS",
      "Accommodation confirmation",
    ],
    stepsToTake: [
      "Attend your university's in-person check-in or complete online check-in.",
      "Collect your student ID card.",
      "Save your student ID number somewhere safe.",
      "Register for the careers service — they can help with part-time work.",
      "Join any student groups relevant to you.",
    ],
    commonMistakes: [
      "Assuming online-only registration is complete — follow up to confirm.",
      "Not registering with the careers service — this is free and useful.",
    ],
    guidanceSlug: "student-status-letter",
    sourceNote: "Your university",
    reminderTrigger: "arrival_date + 3 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D7_002",
    title: "Research and compare UK bank account options",
    stage: "D7",
    category: "Money",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D1_001"],
    whyItMatters:
      "Opening a UK bank account takes time — some banks take 5–10 days. Starting this process in your first week means you will have a working account sooner.",
    whatToPrepare: [
      "Passport",
      "BRP (if collected)",
      "University offer letter or CAS",
      "Proof of UK address (accommodation letter from university or tenancy agreement)",
      "Student ID card",
    ],
    stepsToTake: [
      "Research student bank accounts — traditional banks (Barclays, NatWest) and digital banks (Monzo, Starling).",
      "Digital banks (Monzo, Starling) are often fastest — check if they will accept your documents.",
      "Note which documents each bank requires.",
      "Book a branch appointment if applying with a traditional bank.",
      "Be aware of any minimum deposit requirements.",
      "Compare overdraft limits — student accounts often include an interest-free overdraft.",
    ],
    commonMistakes: [
      "Waiting until you need to pay rent or bills to open an account.",
      "Not checking if your passport and visa are accepted by the bank.",
      "Opening multiple accounts — this can affect your credit score.",
    ],
    guidanceSlug: "student-bank-account-prep",
    sourceNote: "UK Finance · FCA",
    reminderTrigger: "arrival_date + 3 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D7_003",
    title: "Find and register with a local GP near your university",
    stage: "D7",
    category: "Health",
    priority: "Very High",
    required: true,
    dependencyIds: ["STU_D1_001"],
    whyItMatters:
      "GP registration is free and gives you access to the NHS. Without it, you will pay for appointments. In an emergency, being registered means faster care.",
    whatToPrepare: [
      "Your address in the UK",
      "Your previous GP's contact details (for medical records transfer)",
      "Your student ID",
    ],
    stepsToTake: [
      "Use the NHS 'Find a GP' service (nhs.uk) to find doctors near your term-time address.",
      "Check the GP surgery website or call to confirm they are accepting new patients.",
      "Fill in the GMS1 registration form (available from the GP surgery or nhs.uk).",
      "Submit your form in person or online.",
      "You do not need your BRP or visa to register with a GP — it is free for everyone.",
    ],
    commonMistakes: [
      "Thinking you need to pay to see a doctor — NHS GP services are free.",
      "Not registering near your term-time address — you must be registered where you live.",
      "Registering with a GP too far from your accommodation to be useful in an emergency.",
    ],
    guidanceSlug: "how-to-register-with-a-gp",
    sourceNote: "NHS England · UKCISA",
    reminderTrigger: "arrival_date + 5 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D7_004",
    title: "Get your NHS number and understand NHS services",
    stage: "D7",
    category: "Health",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D7_003"],
    whyItMatters:
      "Your NHS number links all your health records in the UK. Knowing how the NHS works means you get the right care at the right time.",
    whatToPrepare: [
      "Your GP registration confirmation",
    ],
    stepsToTake: [
      "Your NHS number will be sent to you by post after GP registration — keep checking your post.",
      "Download the NHS App — you can use it to book appointments, order prescriptions, and view your health records.",
      "Learn the difference between: NHS 111 (non-emergency medical advice), A&E ( emergencies only), your GP (day-to-day care), and pharmacies (minor ailments).",
      "If you need urgent medical help but it is not an emergency — call 111 or visit nhs.uk.",
    ],
    commonMistakes: [
      "Going to A&E for non-emergency issues — use NHS 111 or a walk-in centre instead.",
      "Not knowing your NHS number when you need it — note it once you receive it.",
    ],
    guidanceSlug: "nhs-basics",
    sourceNote: "NHS England",
    reminderTrigger: "arrival_date + 7 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D7_005",
    title: "Activate your student transport discount card",
    stage: "D7",
    category: "Transport",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_D7_001"],
    whyItMatters:
      "Student transport cards give you 30% off rail travel and significant bus savings. The savings quickly outweigh the card cost.",
    whatToPrepare: [
      "A passport-style photo",
      "Your student ID card",
      "Proof of student status",
    ],
    stepsToTake: [
      "Apply for a 16–25 Railcard at railcard.co.uk or from a station — it costs £30 per year and gives 1/3 off rail fares.",
      "Apply for an Oyster Student photocard if you are in London — spreads travel costs across the month.",
      "Download relevant apps (Trainline, National Rail) to plan journeys.",
      "Check if your university offers a campus shuttle or free bus pass.",
    ],
    commonMistakes: [
      "Not carrying your Railcard when travelling — conductors can charge a £10 fine.",
      "Using a non-student Oyster — you will be charged the full adult rate and a penalty.",
    ],
    guidanceSlug: "uk-transport-guide",
    sourceNote: "National Rail · Transport for London",
    reminderTrigger: "arrival_date + 5 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D7_006",
    title: "Understand council tax and student exemption",
    stage: "D7",
    category: "Local Admin",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D1_003"],
    whyItMatters:
      "Council tax can cost over £100 per month if you do not claim the exemption. Students are exempt — but you must tell the council.",
    whatToPrepare: [
      "Your tenancy agreement",
      "Your student status letter (from your university — you need this as proof)",
      "Your UK address",
    ],
    stepsToTake: [
      "Contact your local council (find it at gov.uk/find-your-local-council).",
      "Tell them you are a full-time student and want to claim an exemption.",
      "Submit your student status letter as proof — your university can provide this.",
      "If you live in university halls — your university usually handles this automatically.",
      "Keep records of all correspondence.",
    ],
    commonMistakes: [
      "Ignoring council tax letters — this leads to fines and legal action even if you are exempt.",
      "Assuming you are exempt without informing the council — you must actively claim it.",
      "If you share with non-students — council tax rules become more complex, seek advice.",
    ],
    guidanceSlug: "council-tax-student-exemption",
    sourceNote: "GOV.UK · UKCISA",
    reminderTrigger: "arrival_date + 7 days",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D7_007",
    title: "Join student societies and find local community groups",
    stage: "D7",
    category: "Growth",
    priority: "Low",
    required: false,
    dependencyIds: ["STU_D7_001"],
    whyItMatters:
      "Settling into a new country is easier when you have a community. Universities have hundreds of societies — they are also the best place to meet people.",
    whatToPrepare: [
      "Your student ID",
      "An open mind",
    ],
    stepsToTake: [
      "Attend your university's freshers' fair or welcome fair.",
      "Sign up for at least 1–2 societies — your cultural society and one interest-based group.",
      "Look for international student groups — they understand the specific challenges you face.",
      "Search for local community groups on Facebook or Meetup.",
    ],
    commonMistakes: [
      "Staying isolated — loneliness is common in the first weeks and it gets better.",
      "Joining too many societies and burning out — 1–2 is enough.",
    ],
    sourceNote: "Your university students' union",
    reminderTrigger: "arrival_date + 7 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: false,
    sourceRequired: false,
  },
  {
    taskId: "STU_D7_008",
    title: "Do your first food shop and understand UK supermarkets",
    stage: "D7",
    category: "Local Life",
    priority: "Low",
    required: false,
    dependencyIds: ["STU_D1_001"],
    whyItMatters:
      "Knowing where to shop affordably is part of settling in. UK supermarkets vary significantly in price.",
    whatToPrepare: [
      "A reusable bag (required in most shops — 5p each)",
      "An idea of your weekly food budget",
    ],
    stepsToTake: [
      "Sign up for a loyalty card at Tesco, Sainsbury's, Morrisons, or Lidl — these are free.",
      "For budget shopping — Aldi, Lidl, and Iceland offer the lowest prices.",
      "For everyday mid-range — Tesco, Sainsbury's, and Morrisons.",
      "Try the ethnic supermarkets near your university — they often have ingredients from home at better prices.",
      "Cook in batches if you can — it saves time and money.",
    ],
    commonMistakes: [
      "Shopping at Marks and Spencer or Waitrose daily — it is significantly more expensive.",
      "Not bringing reusable bags — the 5p charge is mandatory at most shops.",
    ],
    sourceNote: "",
    reminderTrigger: "arrival_date + 3 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: false,
    sourceRequired: false,
  },
  {
    taskId: "STU_D7_009",
    title: "Set up utilities if renting privately",
    stage: "D7",
    category: "Accommodation",
    priority: "Medium",
    required: false,
    conditional: true,
    conditionNote: "Only if renting privately — not in university halls",
    dependencyIds: ["STU_D1_003"],
    whyItMatters:
      "If utilities are not in your rent, you must set them up yourself. Failing to do so means no gas, electricity, or internet.",
    whatToPrepare: [
      "Your tenancy agreement (to confirm what is included in rent)",
      "Meter readings from your property",
      "Your bank account details for Direct Debit",
    ],
    stepsToTake: [
      "Check what is included in your rent — if utilities are not included, contact suppliers directly.",
      "Take meter readings on your first day.",
      "Contact the gas and electricity suppliers — find out who the current supplier is from the previous tenant or letting agent.",
      "Set up accounts in your name with your move-in date.",
      "Consider comparison websites for better deals — but read the terms carefully.",
      "Set up water account with your local water company.",
    ],
    commonMistakes: [
      "Missing meter readings — you may end up paying for the previous tenant's usage.",
      "Not setting up an account and being billed at the landlord's rate.",
    ],
    guidanceSlug: "uk-accommodation-guide",
    sourceNote: "Ofgem · Citizens Advice",
    reminderTrigger: "arrival_date + 3 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D7_010",
    title: "Check that your tenancy deposit is protected in a government scheme",
    stage: "D7",
    category: "Accommodation",
    priority: "High",
    required: false,
    conditional: true,
    conditionNote: "Only if you paid a deposit for private rental",
    dependencyIds: ["STU_D7_003"],
    whyItMatters:
      "By law, your landlord must protect your deposit in a government-approved scheme within 30 days. If they do not, you can take legal action and claim compensation.",
    whatToPrepare: [
      "Your tenancy agreement",
      "Your deposit payment receipt",
    ],
    stepsToTake: [
      "Ask your landlord which deposit protection scheme they have used — they must tell you.",
      "Check the scheme directly: MyDeposits, DPS (Deposit Protection Service), or TDS (Tenancy Deposit Scheme).",
      "You should receive a 'certificate of protection' within 30 days of paying your deposit.",
      "If you have not received this — contact Shelter or a student housing advice service.",
    ],
    commonMistakes: [
      "Not knowing which scheme holds your deposit — if the landlord will not tell you, this is a red flag.",
      "Accepting a deduction from your deposit without challenging it — you can dispute deductions.",
    ],
    guidanceSlug: "deposit-protection",
    sourceNote: "GOV.UK · Shelter England · MyDeposits · DPS · TDS",
    reminderTrigger: "arrival_date + 14 days",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },

  // ── FIRST MONTH ──────────────────────────────────────────────────────────
  {
    taskId: "STU_D30_001",
    title: "Open your UK bank account",
    stage: "D30",
    category: "Money",
    priority: "Very High",
    required: true,
    dependencyIds: ["STU_D7_002"],
    whyItMatters:
      "A UK bank account is essential for receiving your student loan or scholarship, paying rent, and proving your financial situation to landlords and employers.",
    whatToPrepare: [
      "Passport",
      "BRP",
      "Proof of UK address (student accommodation letter or tenancy agreement)",
      "University offer letter or CAS",
      "Student ID card",
    ],
    stepsToTake: [
      "Apply online or visit a branch with your chosen bank.",
      "Monzo and Starling can often be opened entirely online — check their apps.",
      "Wait for account activation and card delivery (allow 5–10 working days).",
      "Activate your card and set up online banking.",
      "Add your account details to your student loan or scholarship provider.",
      "Never share your PIN or online banking password with anyone.",
    ],
    commonMistakes: [
      "Using your home country bank account as your primary UK account — international fees add up quickly.",
      "Sharing account details with someone who says they will 'send money' — this is a common scam.",
    ],
    guidanceSlug: "student-bank-account-prep",
    sourceNote: "FCA · UK Finance",
    reminderTrigger: "arrival_date + 14 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_002",
    title: "Register with a GP and book your new patient health check",
    stage: "D30",
    category: "Health",
    priority: "Very High",
    required: true,
    dependencyIds: ["STU_D7_003"],
    whyItMatters:
      "GP registration means you can access free NHS care, book appointments, and get prescriptions. The new patient check helps your GP understand your medical history.",
    whatToPrepare: [
      "Your NHS number (check the NHS App or your registration letter)",
      "Details of any ongoing medications or health conditions",
    ],
    stepsToTake: [
      "Confirm your GP registration is complete.",
      "Book a new patient health check — this is free and usually offered when you register.",
      "Tell your GP about any ongoing health needs, medications, or mental health concerns.",
      "If you take regular medication, confirm your GP can prescribe it in the UK.",
      "Register for the NHS App to manage appointments online.",
    ],
    commonMistakes: [
      "Not telling your GP about existing conditions — they need to know to provide the right care.",
      "Not registering with a dentist — NHS dental care can have long waiting lists.",
    ],
    guidanceSlug: "how-to-register-with-a-gp",
    sourceNote: "NHS England",
    reminderTrigger: "arrival_date + 21 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_003",
    title: "Apply for your National Insurance (NI) number if planning to work",
    stage: "D30",
    category: "Work",
    priority: "High",
    required: false,
    conditional: true,
    conditionNote: "Only if you plan to work in the UK",
    dependencyIds: ["STU_D7_001"],
    whyItMatters:
      "You need an NI number to work legally in the UK. Employers will ask for it. If you are on a Student Route visa, you can work up to 20 hours per week.",
    whatToPrepare: [
      "Your passport or BRP",
      "Your address in the UK",
    ],
    stepsToTake: [
      "You can apply for an NI number at gov.uk/apply-national-insurance-number.",
      "You may be assigned a number automatically when you start work — your employer will tell you.",
      "If you need to call HMRC, the number is on gov.uk/contact-hmrc.",
      "Once you receive your NI number — keep it safe and do not share it publicly.",
    ],
    commonMistakes: [
      "Working without an NI number for too long — speak to your employer about this.",
      "Sharing your NI number publicly or with anyone who is not your employer.",
    ],
    guidanceSlug: "ni-number-basics",
    sourceNote: "GOV.UK (HMRC)",
    reminderTrigger: "arrival_date + 21 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_004",
    title: "Set up your first month's budget and track your spending",
    stage: "D30",
    category: "Money",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_D30_001"],
    whyItMatters:
      "Many students overspend in their first month. Tracking your spending from the start builds good habits and prevents money stress.",
    whatToPrepare: [
      "Your bank account (or several days of transactions to review)",
      "An idea of your expected monthly income (loan, scholarship, support from family)",
    ],
    stepsToTake: [
      "List all expected income for the month.",
      "List essential costs: rent, food, transport, phone, internet.",
      "Set a weekly spending limit for non-essentials.",
      "Use your bank's app to track spending or download a budgeting app.",
      "Save a small emergency fund — even £10–20 per week helps over time.",
    ],
    commonMistakes: [
      "Ignoring your bank balance until it is too late.",
      "Not accounting for one-off costs — textbooks, course equipment, trips home.",
    ],
    guidanceSlug: "first-month-budget",
    sourceNote: "Money Helper (MAS) · StepChange",
    reminderTrigger: "arrival_date + 21 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D30_005",
    title: "Get your student status letter from your university",
    stage: "D30",
    category: "University",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D7_001"],
    whyItMatters:
      "Your student status letter proves you are a full-time student. You need it for council tax exemption, bank accounts, and sometimes visa renewals.",
    whatToPrepare: [
      "Your student ID number",
      "Your reason for needing the letter (e.g., council tax, bank account)",
    ],
    stepsToTake: [
      "Check your university website for the student status letter request form.",
      "Submit the request — it may take 3–5 working days.",
      "Collect the letter and check all details are correct.",
      "Use the letter for council tax exemption, bank account opening, and any other official purposes.",
    ],
    commonMistakes: [
      "Not specifying why you need the letter — some banks or councils require specific wording.",
      "Waiting until the last minute — letter requests can take a week.",
    ],
    guidanceSlug: "student-status-letter",
    sourceNote: "Your university",
    reminderTrigger: "arrival_date + 14 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_006",
    title: "Understand part-time work conditions and your right to work",
    stage: "D30",
    category: "Work",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D7_001"],
    whyItMatters:
      "Working too many hours on a student visa can put your studies and visa status at risk. Knowing the rules protects you.",
    whatToPrepare: [
      "Your visa conditions (check your passport or BRP)",
    ],
    stepsToTake: [
      "Confirm your work rights — Student Route visa holders can work up to 20 hours per week during term time.",
      "Check your CAS or offer letter for any restrictions on your specific course.",
      "Get a copy of your right to work check done by your employer — they are legally required to do this.",
      "Speak to your university careers service before looking for work — they vet employers.",
    ],
    commonMistakes: [
      "Working more than 20 hours a week during term — this can affect your visa.",
      "Not keeping payslips — you need them for your tax records.",
      "Accepting cash-in-hand work — this is illegal and you have no protections.",
    ],
    guidanceSlug: "part-time-work-awareness",
    sourceNote: "UKCISA · GOV.UK",
    reminderTrigger: "arrival_date + 21 days",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_007",
    title: "Review your housing contract and understand your tenant rights",
    stage: "D30",
    category: "Accommodation",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D7_003", "STU_D7_010"],
    whyItMatters:
      "Your tenancy agreement is a legal contract. Understanding it before you sign (or after you have signed) protects you from unexpected costs or unfair terms.",
    whatToPrepare: [
      "Your signed tenancy agreement",
      "Questions about terms you do not understand",
    ],
    stepsToTake: [
      "Read every clause of your tenancy agreement — do not rely on what the landlord told you verbally.",
      "Check: rent amount, deposit amount, notice periods, repair responsibilities, what happens at the end of the tenancy.",
      "If anything is unclear — contact Shelter, your university's housing advice service, or a solicitor.",
      "Keep copies of all correspondence with your landlord.",
    ],
    commonMistakes: [
      "Signing a contract without reading it — verbal promises are not legally binding.",
      "Not knowing your notice period — you may lose your deposit if you do not give enough notice.",
    ],
    guidanceSlug: "tenancy-documents",
    sourceNote: "Shelter England · Citizens Advice",
    reminderTrigger: "arrival_date + 14 days",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_008",
    title: "Set up your council tax account and confirm your student exemption",
    stage: "D30",
    category: "Local Admin",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D7_006", "STU_D30_005"],
    whyItMatters:
      "Council tax bills can arrive quickly and aggressively. Even if you are exempt, ignoring letters leads to fines.",
    whatToPrepare: [
      "Your student status letter",
      "Your UK address",
    ],
    stepsToTake: [
      "If you have not yet contacted your council — do so now.",
      "Submit your student status letter as evidence of exemption.",
      "Ask for written confirmation that your exemption has been applied.",
      "If you receive a bill — do not ignore it. Call the council immediately.",
    ],
    commonMistakes: [
      "Ignoring council letters because you think you are exempt — always respond.",
      "Assuming your university has handled it — check for yourself.",
    ],
    guidanceSlug: "council-tax-student-exemption",
    sourceNote: "GOV.UK · Your local council",
    reminderTrigger: "arrival_date + 21 days",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: true,
  },
  {
    taskId: "STU_D30_009",
    title: "Build a UK CV and learn to spot job scam warning signs",
    stage: "D30",
    category: "Work",
    priority: "Medium",
    required: false,
    dependencyIds: ["STU_D7_001"],
    whyItMatters:
      "A UK-format CV is different from CVs in other countries. Knowing how to spot fake job offers protects you from fraud.",
    whatToPrepare: [
      "Your academic history and qualifications",
      "Your employment history",
      "Details of any relevant skills",
    ],
    stepsToTake: [
      "Visit your university careers service — they offer free CV reviews.",
      "Learn the UK CV format: personal profile, education, experience, skills (not a photo).",
      "Learn common job scam warning signs: guaranteed job offers, upfront fees, too-good salaries.",
      "Only use your university careers service or well-known job sites (Indeed, LinkedIn, Glassdoor).",
    ],
    commonMistakes: [
      "Paying a company to 'guarantee' you a job — this is always a scam.",
      "Including a photo on your CV — this is not standard in the UK.",
    ],
    guidanceSlug: "job-scam-warning",
    sourceNote: "Action Fraud · GOV.UK · Your university careers service",
    reminderTrigger: "arrival_date + 21 days",
    escalationFlag: true,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D30_010",
    title: "Explore UK health services beyond your GP — dentist, optician, pharmacy",
    stage: "D30",
    category: "Health",
    priority: "Medium",
    required: false,
    dependencyIds: ["STU_D30_002"],
    whyItMatters:
      "NHS GP services are free. Other health services (dentist, optician) have costs. Knowing where to go for minor health issues saves time and money.",
    whatToPrepare: [
      "Your NHS number",
      "Your GP's contact details",
    ],
    stepsToTake: [
      "Find an NHS dentist near you — NHS dental treatment costs a fixed band fee (£26.80–£306).",
      "Register with a dentist even before you have a problem — NHS places are limited.",
      "Find your local pharmacy — pharmacists can advise on minor ailments for free.",
      "If you have an existing eye condition, register with an optician for ongoing care.",
    ],
    commonMistakes: [
      "Not registering with a dentist early — NHS dental places fill up quickly.",
      "Going to A&E for dental pain — visit a dentist or call NHS 111 instead.",
    ],
    guidanceSlug: "nhs-basics",
    sourceNote: "NHS England",
    reminderTrigger: "arrival_date + 28 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },

  // ── DAYS 31–90 ───────────────────────────────────────────────────────────
  {
    taskId: "STU_D90_001",
    title: "Review your first month budget and adjust if needed",
    stage: "D90",
    category: "Money",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_D30_004"],
    whyItMatters:
      "Your first month is your baseline. Reviewing it honestly helps you adjust before small overspends become a problem.",
    whatToPrepare: [
      "Your bank statements for the last month",
      "Your original budget",
    ],
    stepsToTake: [
      "Review every transaction from your first month.",
      "Compare actual spending against your plan.",
      "Identify categories where you spent more than expected.",
      "Adjust your second-month budget accordingly.",
      "Look for subscriptions or services you signed up for but do not use.",
    ],
    commonMistakes: [
      "Not reviewing at all — financial problems are easier to fix early.",
      "Cutting essential spending (food, transport) instead of non-essential spending.",
    ],
    guidanceSlug: "first-month-budget",
    sourceNote: "Money Helper (MAS)",
    reminderTrigger: "arrival_date + 35 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_002",
    title: "Check your UK bank account is working well — transfers, payments, overdraft",
    stage: "D90",
    category: "Money",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_D30_001"],
    whyItMatters:
      "Your bank account should work smoothly by now. Any issues with transfers, standing orders, or your overdraft need to be resolved before they cause problems.",
    whatToPrepare: [
      "Your online banking access",
      "Your account and sort code",
    ],
    stepsToTake: [
      "Test sending a small payment to a friend or family member.",
      "Check your overdraft limit and make sure you understand the interest rate.",
      "Check that your student loan or scholarship is going into the right account.",
      "Make sure you understand your bank's charges — overdrafts outside your limit can be expensive.",
    ],
    commonMistakes: [
      "Going over your overdraft limit without knowing — check your balance regularly.",
      "Not updating your bank when you change address.",
    ],
    guidanceSlug: "student-bank-account-prep",
    sourceNote: "FCA",
    reminderTrigger: "arrival_date + 35 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_003",
    title: "Review your housing — is it working? Are there any unresolved issues?",
    stage: "D90",
    category: "Accommodation",
    priority: "Medium",
    required: true,
    dependencyIds: ["STU_D30_007"],
    whyItMatters:
      "After 30 days, you have a better understanding of your housing. Issues that were minor can become serious — it is better to address them now.",
    whatToPrepare: [
      "Your tenancy agreement",
      "A list of any maintenance issues or problems",
    ],
    stepsToTake: [
      "Review: Is the accommodation what you expected? Are there any issues with neighbours, noise, or conditions?",
      "Report any unresolved maintenance issues to your landlord in writing if you have not already.",
      "If you have deposit concerns — check the deposit protection scheme portal.",
      "If you are in university halls, provide feedback to the accommodation office.",
    ],
    commonMistakes: [
      "Waiting until the end of the tenancy to report problems — landlords can use unreported damage against you.",
      "Not knowing who to contact for repairs.",
    ],
    guidanceSlug: "uk-accommodation-guide",
    sourceNote: "Shelter England",
    reminderTrigger: "arrival_date + 60 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_004",
    title: "Update your university with your correct term-time address",
    stage: "D90",
    category: "University",
    priority: "High",
    required: true,
    dependencyIds: ["STU_D30_005"],
    whyItMatters:
      "Your university uses your address for official documents — including your degree certificate and any correspondence from UKVI.",
    whatToPrepare: [
      "Your current UK address",
    ],
    stepsToTake: [
      "Log into your student portal and update your term-time address.",
      "If you have moved since arrival, update your address immediately.",
      "Check your university email regularly for any notices about address requirements.",
      "If you change address again, update it within the timeframe required by your visa (usually 30 days).",
    ],
    commonMistakes: [
      "Not updating your address when you move — your degree certificate may be sent to the wrong address.",
    ],
    sourceNote: "Your university",
    reminderTrigger: "arrival_date + 35 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_005",
    title: "Explore part-time work or internship opportunities",
    stage: "D90",
    category: "Work",
    priority: "Medium",
    required: false,
    dependencyIds: ["STU_D30_003", "STU_D30_006", "STU_D30_009"],
    whyItMatters:
      "Part-time work helps financially and builds your CV. University careers services vet employers and have exclusive opportunities.",
    whatToPrepare: [
      "An updated CV",
      "An idea of how many hours you can work (up to 20 per week during term on a Student Route visa)",
    ],
    stepsToTake: [
      "Visit your university careers service — they post vetted part-time jobs and internships.",
      "Set up job alerts on Indeed, LinkedIn, and Glassdoor for part-time roles.",
      "Consider on-campus jobs — these are often more flexible with your timetable.",
      "Be realistic about how many hours you can manage alongside your studies.",
    ],
    commonMistakes: [
      "Taking on too many hours and affecting your grades.",
      "Not checking your visa work restrictions before accepting a job.",
    ],
    guidanceSlug: "part-time-work-awareness",
    sourceNote: "Your university careers service · UKCISA",
    reminderTrigger: "arrival_date + 45 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_006",
    title: "Complete your 90-day settlement self-review",
    stage: "D90",
    category: "Growth",
    priority: "Low",
    required: true,
    dependencyIds: ["STU_D30_001", "STU_D30_002", "STU_D30_004", "STU_D30_005"],
    whyItMatters:
      "A structured review helps you see what is going well and what still needs attention. It is also useful if you need to report to sponsors or family.",
    whatToPrepare: [
      "Your NewStart UK checklist progress",
      "Notes on what felt difficult or confusing",
    ],
    stepsToTake: [
      "Go through your NewStart UK checklist and mark all completed tasks.",
      "Identify tasks still incomplete and note why.",
      "Reflect: What surprised you most about the UK arrival process? What would you tell someone arriving next year?",
      "Update your sponsor or family on your settlement progress.",
      "Note any questions or concerns for your university or a professional.",
    ],
    commonMistakes: [
      "Not reviewing systematically — small unresolved issues tend to grow.",
    ],
    guidanceSlug: "90-day-review",
    sourceNote: "NewStart UK",
    reminderTrigger: "arrival_date + 90 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_007",
    title: "Understand NHS dental and eye care — register if needed",
    stage: "D90",
    category: "Health",
    priority: "Low",
    required: false,
    dependencyIds: ["STU_D30_010"],
    whyItMatters:
      "NHS dental and eye care have costs and waiting times. Registering early ensures you are not stuck without care when you need it.",
    whatToPrepare: [
      "Your NHS number",
    ],
    stepsToTake: [
      "Register with an NHS dentist if you have not already.",
      "If you need an eye test, find a registered optician near you.",
      "Understand the costs: NHS dental treatment is banded. Eye tests are free for students in Scotland and Wales — check your region.",
    ],
    commonMistakes: [
      "Waiting until you have a dental emergency to find a dentist.",
    ],
    guidanceSlug: "nhs-basics",
    sourceNote: "NHS England",
    reminderTrigger: "arrival_date + 60 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_008",
    title: "Consider opening a savings account for longer-term planning",
    stage: "D90",
    category: "Money",
    priority: "Low",
    required: false,
    dependencyIds: ["STU_D30_004"],
    whyItMatters:
      "If you have any spare income, a savings account builds good financial habits and provides a safety net.",
    whatToPrepare: [
      "Your UK bank account",
      "An idea of how much you can save regularly",
    ],
    stepsToTake: [
      "Check if your current bank offers a savings account.",
      "Compare savings rates — digital banks and ISAs (Individual Savings Accounts) often offer better rates.",
      "Start small — even £5–10 per week builds up.",
      "Do not feel pressured to save if you are struggling financially — prioritise essentials first.",
    ],
    commonMistakes: [
      "Opening multiple savings accounts and losing track of them.",
      "Locking money in a fixed-term account that you might need before it matures.",
    ],
    guidanceSlug: "first-month-budget",
    sourceNote: "Money Helper (MAS) · FCA",
    reminderTrigger: "arrival_date + 60 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_009",
    title: "Build your professional network — careers service, LinkedIn, university events",
    stage: "D90",
    category: "Growth",
    priority: "Low",
    required: false,
    dependencyIds: ["STU_D7_007"],
    whyItMatters:
      "Building professional connections in the UK early in your course gives you more options after graduation.",
    whatToPrepare: [
      "An updated CV",
      "A professional LinkedIn profile",
    ],
    stepsToTake: [
      "Connect with your university careers service and attend at least one event.",
      "Set up a LinkedIn profile — add your university, course, and any relevant experience.",
      "Attend employer recruitment events at your university.",
      "Join relevant professional or cultural networks in your city.",
    ],
    commonMistakes: [
      "Leaving networking until final year — starting early gives you more time.",
    ],
    sourceNote: "Your university careers service · LinkedIn",
    reminderTrigger: "arrival_date + 60 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: true,
    sourceRequired: false,
  },
  {
    taskId: "STU_D90_010",
    title: "Update your family on your settlement progress",
    stage: "D90",
    category: "Growth",
    priority: "Low",
    required: false,
    dependencyIds: ["STU_D90_006"],
    whyItMatters:
      "Your family or sponsors may be supporting you financially or emotionally. Keeping them updated maintains trust and can help if you face any issues.",
    whatToPrepare: [
      "A summary of your settlement progress",
      "Any questions or concerns you want professional advice on",
    ],
    stepsToTake: [
      "Share your 90-day self-review with your sponsor or family.",
      "Tell them about any difficulties — they can often help or direct you to support.",
      "Update them on your finances, health, and academic progress.",
    ],
    commonMistakes: [
      "Not telling sponsors about problems until they become serious.",
    ],
    sourceNote: "",
    reminderTrigger: "arrival_date + 90 days",
    escalationFlag: false,
    adminEditable: true,
    active: true,
    aiHelperAllowed: false,
    sourceRequired: false,
  },
];
